/* GENERATED by scripts/gen-backfilled-icons.mjs - do not edit by hand. */
import { createElement, type ComponentType } from 'react';
import { IconBackfill } from '@glacier/react';
import type { IconProps } from '@glacier/icons';
import {
  Activity as ActivityOutline,
  AlignStartVertical as AlignStartVerticalOutline,
  Apple as AppleOutline,
  ArrowDownToLine as ArrowDownToLineOutline,
  ArrowLeft as ArrowLeftOutline,
  ArrowRight as ArrowRightOutline,
  ArrowUpToLine as ArrowUpToLineOutline,
  Ban as BanOutline,
  BarChart2 as BarChart2Outline,
  Bell as BellOutline,
  BellRing as BellRingOutline,
  Bot as BotOutline,
  Boxes as BoxesOutline,
  Check as CheckOutline,
  ChevronDown as ChevronDownOutline,
  ChevronLeft as ChevronLeftOutline,
  ChevronRight as ChevronRightOutline,
  ChevronUp as ChevronUpOutline,
  Circle as CircleOutline,
  CircleDollarSign as CircleDollarSignOutline,
  CircleDot as CircleDotOutline,
  CircleHelp as CircleHelpOutline,
  CircleMinus as CircleMinusOutline,
  CirclePlus as CirclePlusOutline,
  CircleUserRound as CircleUserRoundOutline,
  Cog as CogOutline,
  Coins as CoinsOutline,
  Compass as CompassOutline,
  Copy as CopyOutline,
  Cpu as CpuOutline,
  Crosshair as CrosshairOutline,
  Crown as CrownOutline,
  Dices as DicesOutline,
  Download as DownloadOutline,
  ExternalLink as ExternalLinkOutline,
  Eye as EyeOutline,
  EyeOff as EyeOffOutline,
  Flag as FlagOutline,
  Flame as FlameOutline,
  Gauge as GaugeOutline,
  Gem as GemOutline,
  Globe as GlobeOutline,
  GraduationCap as GraduationCapOutline,
  Grid3X3 as Grid3X3Outline,
  Hand as HandOutline,
  HardDrive as HardDriveOutline,
  Hash as HashOutline,
  Heart as HeartOutline,
  Hourglass as HourglassOutline,
  House as HouseOutline,
  Image as ImageOutline,
  Info as InfoOutline,
  Keyboard as KeyboardOutline,
  Landmark as LandmarkOutline,
  Layers as LayersOutline,
  LayoutGrid as LayoutGridOutline,
  Library as LibraryOutline,
  Link2 as Link2Outline,
  LogIn as LogInOutline,
  LogOut as LogOutOutline,
  MessageSquare as MessageSquareOutline,
  Minus as MinusOutline,
  Monitor as MonitorOutline,
  Moon as MoonOutline,
  Mountain as MountainOutline,
  Package as PackageOutline,
  Paintbrush as PaintbrushOutline,
  Palette as PaletteOutline,
  PanelRight as PanelRightOutline,
  PanelRightClose as PanelRightCloseOutline,
  PanelRightOpen as PanelRightOpenOutline,
  Paperclip as PaperclipOutline,
  Pause as PauseOutline,
  Percent as PercentOutline,
  PictureInPicture2 as PictureInPicture2Outline,
  Play as PlayOutline,
  Plus as PlusOutline,
  Redo2 as Redo2Outline,
  RefreshCw as RefreshCwOutline,
  Repeat as RepeatOutline,
  RotateCcw as RotateCcwOutline,
  RotateCw as RotateCwOutline,
  ScrollText as ScrollTextOutline,
  Send as SendOutline,
  Settings as SettingsOutline,
  Settings2 as Settings2Outline,
  Shapes as ShapesOutline,
  Share2 as Share2Outline,
  Shield as ShieldOutline,
  Shuffle as ShuffleOutline,
  SkipBack as SkipBackOutline,
  SkipForward as SkipForwardOutline,
  Skull as SkullOutline,
  SlidersHorizontal as SlidersHorizontalOutline,
  Smartphone as SmartphoneOutline,
  Smile as SmileOutline,
  Sparkles as SparklesOutline,
  Star as StarOutline,
  Sun as SunOutline,
  Sunrise as SunriseOutline,
  Swords as SwordsOutline,
  Target as TargetOutline,
  Terminal as TerminalOutline,
  ThumbsUp as ThumbsUpOutline,
  Ticket as TicketOutline,
  Timer as TimerOutline,
  Tornado as TornadoOutline,
  Trash2 as Trash2Outline,
  TriangleAlert as TriangleAlertOutline,
  Trophy as TrophyOutline,
  Undo2 as Undo2Outline,
  Unlink as UnlinkOutline,
  Upload as UploadOutline,
  User as UserOutline,
  UserMinus as UserMinusOutline,
  UserPlus as UserPlusOutline,
  UserRound as UserRoundOutline,
  Users as UsersOutline,
  Wand2 as Wand2Outline,
  Wifi as WifiOutline,
  WifiOff as WifiOffOutline,
  Wrench as WrenchOutline,
  X as XOutline,
  Zap as ZapOutline,
  ZoomIn as ZoomInOutline,
  ZoomOut as ZoomOutOutline,
} from '@glacier/icons';

/**
 * Every icon the app uses, pre-wrapped in IconBackfill.
 *
 * IconBackfill stacks a 33%-opacity silhouette of the glyph behind its own
 * outline, painted from the RESOLVED icon colour - so a muted icon backfills
 * muted and a custom-coloured one keeps its colour, rather than everything
 * turning accent.
 *
 * Wrapped here rather than at 600-odd call sites: the wrapper takes the same
 * props the bare icon did, so `<Swords size={15} />` is unchanged at every
 * one of them and the only edit per file is the import path.
 *
 * ONE DOM CHANGE TO KNOW ABOUT. The rendered node is now a <span> containing
 * two <svg>s, where it used to be a lone <svg>. Descendant selectors are fine;
 * a `> svg` child selector aimed at an icon is not, and the three the app had
 * were rewritten when this landed.
 */
function backfilled(Icon: ComponentType<IconProps>, name: string) {
  const Wrapped = ({ className, style, size, color, ...rest }: IconProps) =>
    createElement(
      IconBackfill,
      // Layout classes belong on the wrapper: it is the box now, and a class
      // put on the inner glyph would style one of two stacked copies.
      // children goes in the props object rather than as a third argument:
      // IconBackfillProps types it as a single element, and createElement's
      // variadic children widen to ReactNode[], which does not satisfy it.
      {
        // A stable hook on every backfilled icon. The rendered node is a span,
        // not an svg, so any CSS that reached an icon as a direct child needs
        // something to aim at that is not an element name - see .pcIcon in
        // cardpopup.css and table.css.
        className: className ? `pcIcon ${className}` : 'pcIcon',
        style,
        size,
        color,
        children: createElement(Icon, { size, color, ...rest }),
      },
    );
  Wrapped.displayName = `Backfilled(${name})`;
  return Wrapped;
}

export const Activity = backfilled(ActivityOutline, 'Activity');
export const AlignStartVertical = backfilled(AlignStartVerticalOutline, 'AlignStartVertical');
export const Apple = backfilled(AppleOutline, 'Apple');
export const ArrowDownToLine = backfilled(ArrowDownToLineOutline, 'ArrowDownToLine');
export const ArrowLeft = backfilled(ArrowLeftOutline, 'ArrowLeft');
export const ArrowRight = backfilled(ArrowRightOutline, 'ArrowRight');
export const ArrowUpToLine = backfilled(ArrowUpToLineOutline, 'ArrowUpToLine');
export const Ban = backfilled(BanOutline, 'Ban');
export const BarChart2 = backfilled(BarChart2Outline, 'BarChart2');
export const Bell = backfilled(BellOutline, 'Bell');
export const BellRing = backfilled(BellRingOutline, 'BellRing');
export const Bot = backfilled(BotOutline, 'Bot');
export const Boxes = backfilled(BoxesOutline, 'Boxes');
export const Check = backfilled(CheckOutline, 'Check');
export const ChevronDown = backfilled(ChevronDownOutline, 'ChevronDown');
export const ChevronLeft = backfilled(ChevronLeftOutline, 'ChevronLeft');
export const ChevronRight = backfilled(ChevronRightOutline, 'ChevronRight');
export const ChevronUp = backfilled(ChevronUpOutline, 'ChevronUp');
export const Circle = backfilled(CircleOutline, 'Circle');
export const CircleDollarSign = backfilled(CircleDollarSignOutline, 'CircleDollarSign');
export const CircleDot = backfilled(CircleDotOutline, 'CircleDot');
export const CircleHelp = backfilled(CircleHelpOutline, 'CircleHelp');
export const CircleMinus = backfilled(CircleMinusOutline, 'CircleMinus');
export const CirclePlus = backfilled(CirclePlusOutline, 'CirclePlus');
export const CircleUserRound = backfilled(CircleUserRoundOutline, 'CircleUserRound');
export const Cog = backfilled(CogOutline, 'Cog');
export const Coins = backfilled(CoinsOutline, 'Coins');
export const Compass = backfilled(CompassOutline, 'Compass');
export const Copy = backfilled(CopyOutline, 'Copy');
export const Cpu = backfilled(CpuOutline, 'Cpu');
export const Crosshair = backfilled(CrosshairOutline, 'Crosshair');
export const Crown = backfilled(CrownOutline, 'Crown');
export const Dices = backfilled(DicesOutline, 'Dices');
export const Download = backfilled(DownloadOutline, 'Download');
export const ExternalLink = backfilled(ExternalLinkOutline, 'ExternalLink');
export const Eye = backfilled(EyeOutline, 'Eye');
export const EyeOff = backfilled(EyeOffOutline, 'EyeOff');
export const Flag = backfilled(FlagOutline, 'Flag');
export const Flame = backfilled(FlameOutline, 'Flame');
export const Gauge = backfilled(GaugeOutline, 'Gauge');
export const Gem = backfilled(GemOutline, 'Gem');
export const Globe = backfilled(GlobeOutline, 'Globe');
export const GraduationCap = backfilled(GraduationCapOutline, 'GraduationCap');
export const Grid3X3 = backfilled(Grid3X3Outline, 'Grid3X3');
export const Hand = backfilled(HandOutline, 'Hand');
export const HardDrive = backfilled(HardDriveOutline, 'HardDrive');
export const Hash = backfilled(HashOutline, 'Hash');
export const Heart = backfilled(HeartOutline, 'Heart');
export const Hourglass = backfilled(HourglassOutline, 'Hourglass');
export const House = backfilled(HouseOutline, 'House');
export const Image = backfilled(ImageOutline, 'Image');
export const Info = backfilled(InfoOutline, 'Info');
export const Keyboard = backfilled(KeyboardOutline, 'Keyboard');
export const Landmark = backfilled(LandmarkOutline, 'Landmark');
export const Layers = backfilled(LayersOutline, 'Layers');
export const LayoutGrid = backfilled(LayoutGridOutline, 'LayoutGrid');
export const Library = backfilled(LibraryOutline, 'Library');
export const Link2 = backfilled(Link2Outline, 'Link2');
export const LogIn = backfilled(LogInOutline, 'LogIn');
export const LogOut = backfilled(LogOutOutline, 'LogOut');
export const MessageSquare = backfilled(MessageSquareOutline, 'MessageSquare');
export const Minus = backfilled(MinusOutline, 'Minus');
export const Monitor = backfilled(MonitorOutline, 'Monitor');
export const Moon = backfilled(MoonOutline, 'Moon');
export const Mountain = backfilled(MountainOutline, 'Mountain');
export const Package = backfilled(PackageOutline, 'Package');
export const Paintbrush = backfilled(PaintbrushOutline, 'Paintbrush');
export const Palette = backfilled(PaletteOutline, 'Palette');
export const PanelRight = backfilled(PanelRightOutline, 'PanelRight');
export const PanelRightClose = backfilled(PanelRightCloseOutline, 'PanelRightClose');
export const PanelRightOpen = backfilled(PanelRightOpenOutline, 'PanelRightOpen');
export const Paperclip = backfilled(PaperclipOutline, 'Paperclip');
export const Pause = backfilled(PauseOutline, 'Pause');
export const Percent = backfilled(PercentOutline, 'Percent');
export const PictureInPicture2 = backfilled(PictureInPicture2Outline, 'PictureInPicture2');
export const Play = backfilled(PlayOutline, 'Play');
export const Plus = backfilled(PlusOutline, 'Plus');
export const Redo2 = backfilled(Redo2Outline, 'Redo2');
export const RefreshCw = backfilled(RefreshCwOutline, 'RefreshCw');
export const Repeat = backfilled(RepeatOutline, 'Repeat');
export const RotateCcw = backfilled(RotateCcwOutline, 'RotateCcw');
export const RotateCw = backfilled(RotateCwOutline, 'RotateCw');
export const ScrollText = backfilled(ScrollTextOutline, 'ScrollText');
export const Send = backfilled(SendOutline, 'Send');
export const Settings = backfilled(SettingsOutline, 'Settings');
export const Settings2 = backfilled(Settings2Outline, 'Settings2');
export const Shapes = backfilled(ShapesOutline, 'Shapes');
export const Share2 = backfilled(Share2Outline, 'Share2');
export const Shield = backfilled(ShieldOutline, 'Shield');
export const Shuffle = backfilled(ShuffleOutline, 'Shuffle');
export const SkipBack = backfilled(SkipBackOutline, 'SkipBack');
export const SkipForward = backfilled(SkipForwardOutline, 'SkipForward');
export const Skull = backfilled(SkullOutline, 'Skull');
export const SlidersHorizontal = backfilled(SlidersHorizontalOutline, 'SlidersHorizontal');
export const Smartphone = backfilled(SmartphoneOutline, 'Smartphone');
export const Smile = backfilled(SmileOutline, 'Smile');
export const Sparkles = backfilled(SparklesOutline, 'Sparkles');
export const Star = backfilled(StarOutline, 'Star');
export const Sun = backfilled(SunOutline, 'Sun');
export const Sunrise = backfilled(SunriseOutline, 'Sunrise');
export const Swords = backfilled(SwordsOutline, 'Swords');
export const Target = backfilled(TargetOutline, 'Target');
export const Terminal = backfilled(TerminalOutline, 'Terminal');
export const ThumbsUp = backfilled(ThumbsUpOutline, 'ThumbsUp');
export const Ticket = backfilled(TicketOutline, 'Ticket');
export const Timer = backfilled(TimerOutline, 'Timer');
export const Tornado = backfilled(TornadoOutline, 'Tornado');
export const Trash2 = backfilled(Trash2Outline, 'Trash2');
export const TriangleAlert = backfilled(TriangleAlertOutline, 'TriangleAlert');
export const Trophy = backfilled(TrophyOutline, 'Trophy');
export const Undo2 = backfilled(Undo2Outline, 'Undo2');
export const Unlink = backfilled(UnlinkOutline, 'Unlink');
export const Upload = backfilled(UploadOutline, 'Upload');
export const User = backfilled(UserOutline, 'User');
export const UserMinus = backfilled(UserMinusOutline, 'UserMinus');
export const UserPlus = backfilled(UserPlusOutline, 'UserPlus');
export const UserRound = backfilled(UserRoundOutline, 'UserRound');
export const Users = backfilled(UsersOutline, 'Users');
export const Wand2 = backfilled(Wand2Outline, 'Wand2');
export const Wifi = backfilled(WifiOutline, 'Wifi');
export const WifiOff = backfilled(WifiOffOutline, 'WifiOff');
export const Wrench = backfilled(WrenchOutline, 'Wrench');
export const X = backfilled(XOutline, 'X');
export const Zap = backfilled(ZapOutline, 'Zap');
export const ZoomIn = backfilled(ZoomInOutline, 'ZoomIn');
export const ZoomOut = backfilled(ZoomOutOutline, 'ZoomOut');
