//! Server-resident AI opponents (PROTOCOL.md, Bots addendum v3).
//!
//! A bot is an ordinary `Player` driven by one scheduler task. Every act goes
//! through `ws::dispatch_action`, the identical pipeline human actions use, so
//! bots obey the same freeform contract: the server records, never judges.
//! Combat damage is settled the same way humans settle it, by the bot adjusting
//! its OWN life and creatures from the shared combat record.
//!
//! The brain is a heuristic player in the Forge tradition (creature evaluation,
//! race math, an aggression ladder, an ordered block pipeline, threat-scored
//! multiplayer targeting) stripped to the data this server actually has: mana
//! value, coarse type letters, and printed power/toughness for the embedded
//! precons, plus whatever stats a combat declaration carries.
//!
//! The scheduler is stateless across restarts: rooms are persisted and
//! reloaded, and scanning them resumes every bot automatically. Per-bot
//! scratch memory (`BotMind`) lives only in this task and self-heals from
//! room state when missing.

use crate::game::{Action, Zone};
use crate::rooms::{Card, Combat, EndedCombat, Player, Room};
use crate::{ws, App};
use serde::Deserialize;
use std::collections::{HashMap, VecDeque};
use std::sync::{Arc, OnceLock};
use std::time::Duration;

// ------------------------------------------------------------ embedded data

/// Generated by scripts/gen-bot-data.mjs from src/data/precons.json.
#[derive(Deserialize)]
pub struct BotData {
    pub decks: Vec<BotDeck>,
    pub attrs: HashMap<String, CardAttr>,
}

#[derive(Deserialize)]
pub struct BotDeck {
    pub code: String,
    pub name: String,
    pub cards: Vec<BotDeckCard>,
}

#[derive(Deserialize)]
pub struct BotDeckCard {
    pub sid: String,
    pub name: String,
    pub qty: u32,
    pub board: String,
}

/// Per-card attributes: mana value, type letters (subset of LCISAEPB, O =
/// other), and printed power/toughness when present.
#[derive(Deserialize)]
pub struct CardAttr {
    pub mv: f64,
    pub t: String,
    #[serde(default)]
    pub p: Option<String>,
    #[serde(default)]
    pub tg: Option<String>,
}

static DATA: OnceLock<BotData> = OnceLock::new();

pub fn data() -> &'static BotData {
    DATA.get_or_init(|| {
        serde_json::from_str(include_str!("data/bot_data.json")).expect("bot_data.json parses")
    })
}

// ----------------------------------------------------------------- identity

const PERSONAS: [&str; 6] = ["Aster", "Bramble", "Cirrus", "Moss", "Quill", "Wren"];

/// An unused persona username for this room ("Aster (AI)"); numbered fallback
/// if the pool is somehow exhausted.
pub fn pick_name(room: &Room) -> String {
    let start = rand::random_range(0..PERSONAS.len());
    for i in 0..PERSONAS.len() {
        let name = format!("{} (AI)", PERSONAS[(start + i) % PERSONAS.len()]);
        if !room.players.iter().any(|p| p.username == name) {
            return name;
        }
    }
    format!("{} {} (AI)", PERSONAS[start], crate::hex_id(2))
}

/// A deterministic playmat per persona so the same bot always brings the same
/// felt. Every id is in ws::PLAYMATS.
pub fn bot_playmat(username: &str) -> &'static str {
    const MATS: [&str; 6] =
        ["arcane-study", "fae-glade", "planar-sky", "deep-field", "aurora-drift", "tavern"];
    let h = username.bytes().fold(0usize, |a, b| a.wrapping_mul(31).wrapping_add(b as usize));
    MATS[h % MATS.len()]
}

// ------------------------------------------------------------ card reading

pub fn attr(card: &Card) -> Option<&'static CardAttr> {
    card.scryfall_id.as_deref().and_then(|sid| data().attrs.get(sid))
}

/// Known to be a land. Cards outside the embedded attribute table (anything
/// beyond the bundled precons) answer `false`, so callers get silence rather
/// than a guess - which is the right failure for both the bot and the coach.
pub fn is_land(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('L')).unwrap_or(false)
}

/// A creature as far as the bot can tell: typed C in the embedded attrs, or
/// carrying printed/declared power (tokens, opponents' declared stats).
fn is_creature(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('C')).unwrap_or(false) || card.power.is_some()
}

/// Instant or sorcery: rides the stack and self-resolves to the graveyard.
fn is_spell(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('I') || a.t.contains('S')).unwrap_or(false)
}

fn mana_value(card: &Card) -> i64 {
    attr(card).map(|a| a.mv.round() as i64).unwrap_or(0)
}

fn stat(s: Option<&str>) -> Option<i64> {
    s.and_then(|v| v.trim().parse::<i64>().ok())
}

fn power(card: &Card) -> i64 {
    stat(card.power.as_deref())
        .or_else(|| attr(card).and_then(|a| stat(a.p.as_deref())))
        .unwrap_or(0)
}

fn toughness(card: &Card) -> i64 {
    stat(card.toughness.as_deref())
        .or_else(|| attr(card).and_then(|a| stat(a.tg.as_deref())))
        .unwrap_or(0)
}

/// Forge-style creature value, stripped to the visible stats. Mana value
/// stands in for the rules text the server cannot see: an expensive creature
/// probably does something.
fn eval_creature(card: &Card) -> i64 {
    100 + 15 * power(card) + 10 * toughness(card) + 5 * mana_value(card)
}

/// The card that a combat entry describes, wherever it currently sits, with
/// its owner's seat. None once it left every battlefield.
fn find_on_battlefields<'a>(room: &'a Room, iid: &str) -> Option<(usize, &'a Card)> {
    room.players.iter().find_map(|p| {
        p.battlefield.iter().find(|c| c.iid == iid).map(|c| (p.seat, c))
    })
}

// -------------------------------------------------------------------- style

#[derive(Clone, Copy, PartialEq)]
enum Style {
    Casual,
    Aggro,
    Defensive,
}

fn style_of(p: &Player) -> Style {
    match p.bot_style.as_deref() {
        Some("aggro") => Style::Aggro,
        Some("defensive") => Style::Defensive,
        _ => Style::Casual,
    }
}

/// Spells the bot is willing to cast in one of its turns (commander is free).
fn cast_budget(style: Style) -> u32 {
    match style {
        Style::Casual => 2,
        Style::Aggro => 3,
        Style::Defensive => 2,
    }
}

/// Baseline aggression on the Forge 0-5 ladder before race math adjusts it.
fn base_aggression(style: Style) -> i32 {
    match style {
        Style::Aggro => 4,
        Style::Casual => 3,
        Style::Defensive => 2,
    }
}

/// Difficulty tier: -1 easy, 0 normal, +1 hard. Shifts aggression and the
/// casting budget; easy also stops gang- and chump-blocking (see choose_block)
/// and keeps almost any opening hand.
fn tier_of(p: &Player) -> i32 {
    match p.bot_difficulty.as_deref() {
        Some("easy") => -1,
        Some("hard") => 1,
        _ => 0,
    }
}

/// Enforced rooms: can this creature legally be declared an attacker?
fn attack_legal(app: &App, room: &Room, card: &Card) -> bool {
    if !crate::rules::enforced(room) {
        return true;
    }
    let f = crate::rules::facts(app, card);
    let sick = card.entered_turn == Some(room.turn_number)
        && !f.as_ref().map(|f| f.has("haste")).unwrap_or(false);
    if sick {
        return false;
    }
    !f.map(|f| f.has("defender")).unwrap_or(false)
}

/// Enforced rooms: may `blocker` legally block `attacker`? Delegates to the
/// validator's full evasion table (flying, fear, shadow, skulk, protection,
/// ...), so the bot never proposes a block the engine would reject.
fn block_legal(app: &App, room: &Room, blocker: &Card, attacker: &Card) -> bool {
    if !crate::rules::enforced(room) {
        return true;
    }
    crate::rules::may_block(app, room, blocker, attacker).is_ok()
}

/// Enforced rooms: does this seat defend against the declared attack?
fn defends_enforced(room: &Room, combat: &Combat, seat: usize) -> bool {
    let fallback = room
        .players
        .iter()
        .filter(|p| p.seat != room.active_seat && !p.conceded)
        .map(|p| p.seat)
        .min();
    combat
        .attackers
        .iter()
        .any(|a| a.defender_seat.or(fallback) == Some(seat))
}

// --------------------------------------------------------------- table talk

fn pick<'a>(pool: &[&'a str]) -> &'a str {
    pool[rand::random_range(0..pool.len())]
}

pub fn greeting_line() -> String {
    pick(&[
        "Hey table, good luck everyone!",
        "Shuffling up. This should be fun.",
        "I brought one of the house decks. Be gentle.",
        "Ready when you are!",
    ])
    .to_string()
}

fn keep_line() -> String {
    pick(&[
        "I'll keep this hand.",
        "Keeping. Looks playable.",
        "This will do.",
    ])
    .to_string()
}

fn mull_line(down_to: usize) -> String {
    match rand::random_range(0..3) {
        0 => format!("Not a fan of these. Going to {down_to}."),
        1 => format!("Mulligan for me, down to {down_to}."),
        _ => format!("These cards owe me an apology. Taking a mulligan to {down_to}."),
    }
}

fn gg_line() -> String {
    pick(&[
        "That's it for me. GG all!",
        "I'm done for. Good game!",
        "You got me. GG!",
    ])
    .to_string()
}

fn win_line() -> String {
    pick(&[
        "GG everyone, that was fun!",
        "Good game, all!",
        "GG! The house deck delivers.",
    ])
    .to_string()
}

fn commander_line(name: &str) -> String {
    match rand::random_range(0..3) {
        0 => format!("Casting my commander, {name}!"),
        1 => format!("Here comes {name}."),
        _ => format!("{name} joins the party."),
    }
}

/// "Attacking Matt for 12 damage with A, B and C." Creature list capped at
/// three names, the rest folded into a count.
fn attack_line(defender: &str, total: i64, names: &[String]) -> String {
    let listed = match names.len() {
        0 => "nothing".to_string(),
        1 => names[0].clone(),
        2 => format!("{} and {}", names[0], names[1]),
        3 => format!("{}, {} and {}", names[0], names[1], names[2]),
        n => format!("{}, {} and {} more", names[0], names[1], n - 2),
    };
    format!("Attacking {defender} for {total} damage with {listed}.")
}

fn block_line(blocker: &str, attacker: &str) -> String {
    match rand::random_range(0..3) {
        0 => format!("Blocking {attacker} with {blocker}."),
        1 => format!("{blocker} steps in front of {attacker}."),
        _ => format!("I'll put {blocker} in the way of {attacker}."),
    }
}

fn damage_line(taken: i64, life_after: i64) -> String {
    match rand::random_range(0..3) {
        0 => format!("Ouch, {taken} damage. I'm at {life_after}."),
        1 => format!("Taking {taken}. That puts me at {life_after} life."),
        _ => format!("{taken} damage goes through. Down to {life_after}."),
    }
}

// -------------------------------------------------------------------- mind

/// Payment in progress: tap `taps` one per tick, then fire the spell.
struct CastPlan {
    iid: String,
    from_command: bool,
    taps: Vec<String>,
    to_stack: bool,
    /// A chat line to send the tick the spell actually fires.
    announce: Option<String>,
}

/// The bot's declared offense this turn: attackers still to declare, then an
/// announcement, then a response window that watches the DEFENDER rather than
/// just a clock - combat stays open while a human is still reacting.
struct AttackPlan {
    defender_seat: usize,
    /// Attacker iids not yet declared (drained one per tick).
    pending: Vec<String>,
    announced: bool,
    /// When the announcement went out (unix ms; 0 = not yet).
    announced_at: i64,
    /// The defender's life total at announcement, to notice them settling
    /// the damage themselves.
    defender_life: i64,
    /// Blocks visible at the last tick, to notice new declarations.
    blocks_seen: usize,
    /// When a defender response was noticed: end shortly after, leaving room
    /// for a second block or a change of mind.
    respond_grace_until: i64,
    /// Enforced rooms: combat.lock still owed (sent with the announcement).
    needs_lock: bool,
}

/// In-memory scratch for one bot. Never persisted; everything here self-heals
/// from room state (worst case after a restart: an extra land drop or a
/// forgotten damage bookkeeping entry).
#[derive(Default)]
struct BotMind {
    /// Bookkeeping actions queued for later ticks (post-combat life, deaths).
    queue: VecDeque<Action>,
    /// (turn round, unix ms) when this bot's actionable turn began.
    turn_started: Option<(u64, i64)>,
    /// Turn round the bot last played a land in (or gave up looking).
    land_turn: Option<u64>,
    /// (turn round, spells cast so far that round).
    casts: (u64, u32),
    casting: Option<CastPlan>,
    attack: Option<AttackPlan>,
    /// Cards this bot put onto the battlefield this turn round: they are
    /// "summoning sick" and never attack the turn they arrive.
    played_this_turn: Vec<String>,
    /// seq of the last ended combat this bot settled (idempotent, from
    /// room.last_combat). A fresh mind adopts the current marker instead of
    /// settling history (restart safety).
    settled_combat: Option<u64>,
    adopted: bool,
    /// Chat lines spoken about blocks in the combat currently on the table.
    block_says: u32,
    said_gg: bool,
    said_win: bool,
}

/// A bot never chews on one turn longer than this before passing. Its own
/// attack's response window is exempt (that clock belongs to the defender).
const TURN_FAILSAFE_MS: i64 = 35_000;
/// ...and never acts on a fresh turn faster than this. A bot that answers
/// the instant the turn arrives reads as a glitch, not an opponent - even
/// at an all-bot table someone may be spectating.
const TURN_MIN_THINK_MS: i64 = 500;
/// Attack response windows. Against humans the bot holds combat open until
/// the defender actually responds (blocks settle, life adjusts, or they end
/// combat themselves), up to a generous cap; a response is followed by a
/// short grace so a second block or a change of mind still fits. All-bot
/// tables need none of that.
const ATTACK_WAIT_HUMAN_MAX_MS: i64 = 45_000;
const ATTACK_RESPONSE_GRACE_MS: i64 = 4_000;
const ATTACK_WAIT_BOTS_MS: i64 = 1_600;

/// One decision per bot per tick: at most one game action plus any table talk.
/// `fast` marks mechanical bookkeeping (payment taps, damage settlement) the
/// scheduler may chain several of in one tick - a human taps five lands in a
/// second too; it is the DECISIONS that deserve the human pacing.
struct Decision {
    action: Option<Action>,
    say: Vec<String>,
    fast: bool,
}

impl Decision {
    fn none() -> Self {
        Decision { action: None, say: Vec::new(), fast: false }
    }
    fn act(action: Action) -> Self {
        Decision { action: Some(action), say: Vec::new(), fast: false }
    }
    fn fast(action: Action) -> Self {
        Decision { action: Some(action), say: Vec::new(), fast: true }
    }
}

// --------------------------------------------------------------- scheduler

/// One task for the whole server: every ~800ms, give each bot in each room at
/// most one action. Room ids are collected first and each room is locked on
/// its own; no DashMap ref is ever held across an await.
pub async fn scheduler(app: Arc<App>) {
    let mut minds: HashMap<(String, String), BotMind> = HashMap::new();
    let mut interval = tokio::time::interval(Duration::from_millis(800));
    interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
    loop {
        interval.tick().await;
        let room_ids: Vec<String> = app
            .rooms
            .iter()
            .filter(|r| r.players.iter().any(|p| p.is_bot))
            .map(|r| r.id.clone())
            .collect();
        for rid in &room_ids {
            let Some(mut room) = app.rooms.get_mut(rid) else {
                continue;
            };
            let bots: Vec<String> = room
                .players
                .iter()
                .filter(|p| p.is_bot)
                .map(|p| p.user_id.clone())
                .collect();
            for uid in bots {
                let mind = minds.entry((rid.clone(), uid.clone())).or_default();
                // Mechanical bookkeeping chains within one tick (capped);
                // anything decision-shaped ends the bot's tick.
                for _ in 0..5 {
                    let decision = decide(&app, &room, &uid, mind, crate::now_ms());
                    if !decision.say.is_empty() {
                        let username = room
                            .players
                            .iter()
                            .find(|p| p.user_id == uid)
                            .map(|p| p.username.clone())
                            .unwrap_or_default();
                        for line in &decision.say {
                            ws::bot_chat(&app, &room, &uid, &username, line);
                        }
                    }
                    let Some(action) = decision.action else { break };
                    if let Err((code, msg)) =
                        ws::dispatch_action(&app, &mut room, &uid, action, None)
                    {
                        eprintln!("bot {uid} in room {rid}: {code}: {msg}");
                        // Enforced tables surface a rejected bot action to the
                        // room log: a bot proposing an illegal move is an
                        // engine bug, and the fuzz playtest asserts none
                        // appear. (match_over is the room freezing mid-plan,
                        // not an illegal move.)
                        if crate::rules::enforced(&room) && code != "match_over" {
                            let username = room
                                .players
                                .iter()
                                .find(|p| p.user_id == uid)
                                .map(|p| p.username.clone())
                                .unwrap_or_default();
                            room.seq += 1;
                            let seq = room.seq;
                            ws::room_log(
                                &app,
                                &room,
                                seq,
                                &format!("[rules] {username}'s move was rejected: {msg}"),
                            );
                        }
                        break;
                    }
                    if !decision.fast {
                        break;
                    }
                }
            }
        }
        // Drop scratch for bots or rooms that no longer exist.
        minds.retain(|(rid, uid), _| {
            app.rooms
                .get(rid)
                .map(|r| r.players.iter().any(|p| p.user_id == *uid))
                .unwrap_or(false)
        });
    }
}

// -------------------------------------------------------------------- brain

/// The bot's one decision for this tick.
fn decide(app: &App, room: &Room, uid: &str, mind: &mut BotMind, now: i64) -> Decision {
    let Some(me) = room.players.iter().find(|p| p.user_id == uid) else {
        return Decision::none();
    };
    if !room.started {
        return Decision::none();
    }
    if let Some(result) = &room.match_result {
        // The table is frozen, but a winning bot still gets its handshake in.
        if result.winner_user_id == me.user_id && !mind.said_win {
            mind.said_win = true;
            return Decision { action: None, say: vec![win_line()], fast: false };
        }
        return Decision::none();
    }
    if me.conceded {
        return Decision::none();
    }
    let style = style_of(me);
    let mut say: Vec<String> = Vec::new();

    // A combat that ended (combat.end, or cleared by a turn change) settles
    // its damage against this bot from the room's authoritative record; a
    // fast attack sequence can begin and end entirely between two ticks, so
    // a live snapshot could never be trusted to exist. Enforced rooms skip
    // all of it - combat.resolve already applied damage and deaths.
    if crate::rules::enforced(room) {
        mind.adopted = true;
        mind.settled_combat = room.last_combat.as_ref().map(|e| e.seq);
    } else if room.combat.is_none() {
        mind.block_says = 0;
        match (&room.last_combat, mind.adopted) {
            (Some(ended), true) => {
                if mind.settled_combat != Some(ended.seq) {
                    mind.settled_combat = Some(ended.seq);
                    settle_combat(room, me, ended, mind, &mut say);
                }
            }
            (ended, false) => {
                // A brand-new mind (boot/restart) must not re-settle a combat
                // that ended before it existed.
                mind.adopted = true;
                mind.settled_combat = ended.as_ref().map(|e| e.seq);
            }
            (None, true) => {}
        }
    } else if !mind.adopted {
        mind.adopted = true;
        mind.settled_combat = room.last_combat.as_ref().map(|e| e.seq);
    }
    if let Some(action) = mind.queue.pop_front() {
        return Decision { action: Some(action), say, fast: true };
    }

    // Dead by the numbers: concede so the match can actually end.
    let cmd_dead = me.cmd_damage.values().any(|&d| d >= 21);
    if me.life <= 0 || me.poison >= 10 || cmd_dead {
        if !mind.said_gg {
            mind.said_gg = true;
            say.push(gg_line());
        }
        return Decision { action: Some(Action::Concede), say, fast: false };
    }

    // Own mulligan first; it blocks everything else this bot might do.
    if let Some(m) = &me.mulligan {
        if m.state == "deciding" {
            let (action, line) = mulligan_action(room, me, m.taken);
            if let Some(line) = line {
                say.push(line);
            }
            return Decision { action: Some(action), say, fast: false };
        }
    }

    // Commander headed off the battlefield: always accept the command zone.
    if let Some(p) = room.pending_cmd.iter().find(|p| p.owner == uid) {
        return Decision { action: Some(Action::CmdReturn { iid: p.iid.clone(), accept: true }), say, fast: false };
    }

    // A fired trigger of mine: apply what the engine parsed and say so;
    // triggers only a human could perform are dismissed (their text is table
    // knowledge either way). `fast` so a burst of triggers clears in one tick.
    if crate::rules::enforced(room) {
        if let Some(pt) = room.pending_triggers.iter().find(|t| t.owner == uid) {
            if pt.auto {
                say.push(format!(
                    "{} triggers: {}.",
                    pt.source_name,
                    crate::rules::effects_summary(&pt.effects)
                ));
            }
            return Decision {
                action: Some(Action::TriggerAnswer { id: pt.id.clone(), apply: pt.auto }),
                say,
                fast: true,
            };
        }
    }

    // Wait politely while anyone is still deciding their mulligan. Conceded
    // seats never keep (their decision is void), so they do not hold this up.
    let all_kept = room
        .players
        .iter()
        .filter(|p| !p.conceded)
        .all(|p| p.mulligan.as_ref().map(|m| m.state == "kept").unwrap_or(true));
    if !all_kept {
        return Decision { action: None, say, fast: false };
    }

    // An open stack (enforced): resolve my own top spell once everyone has
    // passed, respond rarely (hard bots with a spare instant), else pass.
    if crate::rules::enforced(room) && !room.stack.is_empty() {
        let top = room.stack.last().unwrap();
        if top.owner == me.user_id {
            if crate::rules::stack_resolvable(room, me.seat) {
                // Permanents (a cascade hit riding the stack) resolve onto
                // the battlefield; instants and sorceries to the graveyard.
                let to_battlefield = crate::rules::facts(app, &top.card)
                    .map(|f| f.is_permanent() || f.is_land())
                    .unwrap_or(false);
                let k = me.battlefield.iter().filter(|c| !is_land(c)).count();
                return Decision {
                    action: Some(Action::StackResolve {
                        iid: top.card.iid.clone(),
                        to: if to_battlefield { Zone::Battlefield } else { Zone::Graveyard },
                        x: to_battlefield.then(|| (0.15 + 0.11 * (k % 7) as f64).min(0.92)),
                        y: to_battlefield.then_some(0.5),
                    }),
                    say,
                    fast: false,
                };
            }
            return Decision { action: None, say, fast: false };
        }
        if !room.stack_passed.contains(&me.seat) {
            // The threat table: a recognized removal/burn spell from an
            // opponent, while I have a board, is answered by a hard bot every
            // time; otherwise hard bots respond occasionally.
            let threatened = crate::rules::facts(app, &top.card)
                .map(|f| f.threat)
                .unwrap_or(false)
                && me.battlefield.iter().any(is_creature);
            if tier_of(me) > 0 && (threatened || rand::random_range(0..100) < 30) {
                let response = me.hand.iter().find(|c| {
                    crate::rules::facts(app, c)
                        .map(|f| {
                            (f.is_instant() || f.has("flash"))
                                && crate::rules::can_afford(
                                    app,
                                    me,
                                    crate::rules::reduced_generic(app, me, &f, f.generic),
                                    &f.pips,
                                )
                        })
                        .unwrap_or(false)
                });
                if let Some(card) = response {
                    return Decision {
                        action: Some(Action::Cast {
                            iid: card.iid.clone(),
                            payment: None,
                            x: Some(0.5),
                            y: Some(0.5),
                        }),
                        say,
                        fast: false,
                    };
                }
            }
            return Decision { action: Some(Action::StackPass), say, fast: true };
        }
        return Decision { action: None, say, fast: false };
    }

    // Someone else's combat: declare blocks, one per tick.
    if let Some(combat) = &room.combat {
        if room.active_seat != me.seat {
            if crate::rules::enforced(room) {
                // Enforced machine: wait for the lock, block, then Ready.
                if !combat.locked || combat.blocks_ready {
                    return Decision { action: None, say, fast: false };
                }
                if !defends_enforced(room, combat, me.seat) {
                    return Decision { action: None, say, fast: false };
                }
                if let Some(action) = choose_block(app, room, me, combat, style, mind, &mut say) {
                    return Decision { action: Some(action), say, fast: false };
                }
                return Decision { action: Some(Action::CombatReady), say, fast: false };
            }
            if let Some(action) = choose_block(app, room, me, combat, style, mind, &mut say) {
                return Decision { action: Some(action), say, fast: false };
            }
            return Decision { action: None, say, fast: false };
        }
    }

    if room.active_seat != me.seat {
        return Decision { action: None, say, fast: false };
    }
    let mut d = own_turn(app, room, me, mind, style, now);
    if !say.is_empty() {
        let mut merged = say;
        merged.extend(d.say);
        d.say = merged;
    }
    d
}

// ----------------------------------------------------------------- mulligan

/// The free-mulligan allowance for this room (mirrors turns.rs).
fn free_mulls(room: &Room) -> u32 {
    if room.settings.unlimited_mulligans {
        return u32::MAX;
    }
    if let Some(n) = room.settings.free_mulligans {
        return n;
    }
    let commander_ish = crate::rooms::format_has_commander(&room.format);
    if commander_ish && room.players.len() >= 3 {
        1
    } else {
        0
    }
}

/// XMage's one-line rule, scaled to the dealt hand: keep 2..=n-2 lands in a
/// hand of n (minimum bound 1 for tiny hands); never mulligan below 5 cards.
/// Returns the action plus an optional chat line.
fn mulligan_action(room: &Room, me: &Player, taken: u32) -> (Action, Option<String>) {
    let hand = me.hand.len();
    let lands = me.hand.iter().filter(|c| is_land(c)).count();
    let lo = if hand <= 5 { 1 } else { 2 };
    let hi = hand.saturating_sub(2).max(lo);
    let full = crate::game::effective_hand_size(room);
    let can_dig = hand > 5 || room.settings.unlimited_mulligans;
    if !(lo..=hi).contains(&lands) && can_dig && taken < 3 {
        // Vancouver draws one fewer next hand; London re-draws full then
        // bottoms, so "down to" reads off the owed count either way.
        let owed = (taken + 1).saturating_sub(free_mulls(room)) as usize;
        let down_to = full.saturating_sub(owed).max(1);
        return (Action::MullTake, Some(mull_line(down_to)));
    }

    // Keeping: London owes exactly max(taken - free, 0) cards to the bottom;
    // Vancouver owes none. Bottom the most expensive spells first, holding on
    // to three lands where possible.
    let owed = if crate::game::is_vancouver(room) {
        0
    } else {
        taken.saturating_sub(free_mulls(room)) as usize
    };
    let mut ranked: Vec<(u8, i64, String)> = Vec::new();
    let mut lands_seen = 0u32;
    for c in &me.hand {
        if is_land(c) {
            lands_seen += 1;
            // The first three lands are bottomed only as a last resort.
            let tier = if lands_seen <= 3 { 2 } else { 1 };
            ranked.push((tier, 0, c.iid.clone()));
        } else {
            ranked.push((0, -mana_value(c), c.iid.clone()));
        }
    }
    ranked.sort();
    let bottom_iids: Vec<String> =
        ranked.into_iter().take(owed.min(me.hand.len())).map(|(_, _, iid)| iid).collect();
    (Action::MullKeep { bottom_iids }, Some(keep_line()))
}

// ----------------------------------------------------------- combat: settle

/// True when `a` (an attacker record) is aimed at `seat`: explicitly, or
/// implicitly in a two-player game where there is only one possible defender.
fn aimed_at(a: &crate::rooms::Attacker, seat: usize, two_player: bool) -> bool {
    match a.defender_seat {
        Some(d) => d == seat,
        None => two_player,
    }
}

/// A combat ended: settle everything that concerns this bot.
/// - As the defender: apply unblocked damage to its own life (commander
///   attackers via cmd.damage, which also lowers life), and put its own dead
///   blockers into the graveyard.
/// - As the attacker: put its own dead attackers into the graveyard.
/// It never touches anyone else's cards or totals.
fn settle_combat(room: &Room, me: &Player, ended: &EndedCombat, mind: &mut BotMind, say: &mut Vec<String>) {
    let combat = &ended.combat;
    let live = room.players.iter().filter(|p| !p.conceded).count();
    let two_player = live <= 2;
    let mut life_loss = 0i64;
    let mut cmd_loss = 0i64;

    for a in &combat.attackers {
        let found = find_on_battlefields(room, &a.iid);
        let mine = me.battlefield.iter().any(|c| c.iid == a.iid);
        let blockers: Vec<&crate::rooms::Block> =
            combat.blocks.iter().filter(|b| b.attacker_iid == a.iid).collect();

        if mine {
            // My attacker: dies when the blockers' combined power gets there.
            let atough = stat(a.toughness.as_deref())
                .or_else(|| found.map(|(_, c)| toughness(c)))
                .unwrap_or(0);
            let incoming: i64 = blockers
                .iter()
                .map(|b| {
                    stat(b.power.as_deref())
                        .or_else(|| {
                            find_on_battlefields(room, &b.blocker_iid).map(|(_, c)| power(c))
                        })
                        .unwrap_or(0)
                })
                .sum();
            if !blockers.is_empty() && atough > 0 && incoming >= atough {
                mind.queue.push_back(Action::CardMove {
                    iid: a.iid.clone(),
                    to: Zone::Graveyard,
                    x: None,
                    y: None,
                    index: None,
                    face_down: false,
                });
            }
            continue;
        }

        // Someone else's attacker. Ignore it unless it was aimed at me.
        if !aimed_at(a, me.seat, two_player) {
            continue;
        }
        let owner_seat = found.map(|(seat, _)| seat);
        if owner_seat == Some(me.seat) {
            continue;
        }
        let apower = stat(a.power.as_deref())
            .or_else(|| found.map(|(_, c)| power(c)))
            .unwrap_or(0);

        // My blockers on it: each dies if the attacker's power covers its
        // toughness. (The attacker's own death is its owner's to record.)
        for b in &blockers {
            let Some(bl) = me.battlefield.iter().find(|c| c.iid == b.blocker_iid) else {
                continue; // another defender's blocker, not mine to move
            };
            let btough = stat(b.toughness.as_deref()).unwrap_or_else(|| toughness(bl));
            if apower > 0 && apower >= btough {
                mind.queue.push_back(Action::CardMove {
                    iid: bl.iid.clone(),
                    to: Zone::Graveyard,
                    x: None,
                    y: None,
                    index: None,
                    face_down: false,
                });
            }
        }
        if !blockers.is_empty() || apower <= 0 {
            continue;
        }

        // Unblocked damage to me. Commander damage IS life loss server-side,
        // so a commander attacker goes through cmd.damage alone; anything
        // else is a plain life adjustment.
        let is_cmd = found.map(|(_, c)| c.is_commander).unwrap_or(false);
        if is_cmd {
            if let Some(owner_seat) = owner_seat {
                cmd_loss += apower;
                mind.queue.push_back(Action::CmdDamage {
                    from_seat: owner_seat,
                    delta: apower,
                    commander_iid: Some(a.iid.clone()),
                });
            } else {
                life_loss += apower;
            }
        } else {
            life_loss += apower;
        }
    }

    if life_loss > 0 {
        mind.queue.push_front(Action::LifeAdd { delta: -life_loss });
    }
    let total = life_loss + cmd_loss;
    if total > 0 {
        say.push(damage_line(total, me.life - total));
    }
}

// ----------------------------------------------------------- combat: blocks

/// The Forge-ish ordered block pipeline, one declaration per tick:
/// 1. free blocks (kill and survive), 2. profitable trades, 3. gang blocks on
/// the biggest attacker, 4. chump blocks when life is actually in danger.
/// Attacker stats come from the combat declaration (the attacking client
/// knows its own counters); blocker stats from the embedded attrs.
fn choose_block(
    app: &App,
    room: &Room,
    me: &Player,
    combat: &Combat,
    style: Style,
    mind: &mut BotMind,
    say: &mut Vec<String>,
) -> Option<Action> {
    let tier = tier_of(me);
    let live = room.players.iter().filter(|p| !p.conceded).count();
    let two_player = live <= 2;

    // Attackers aimed at me, with their declared stats and block status.
    struct Atk<'a> {
        a: &'a crate::rooms::Attacker,
        card: Option<&'a Card>,
        power: i64,
        toughness: i64,
        name: String,
        blocked: bool,
    }
    let mut incoming: Vec<Atk> = combat
        .attackers
        .iter()
        .filter(|a| aimed_at(a, me.seat, two_player))
        .filter_map(|a| {
            let found = find_on_battlefields(room, &a.iid);
            if let Some((owner_seat, _)) = found {
                if owner_seat == me.seat {
                    return None;
                }
            }
            let p = stat(a.power.as_deref()).or_else(|| found.map(|(_, c)| power(c))).unwrap_or(0);
            let t = stat(a.toughness.as_deref())
                .or_else(|| found.map(|(_, c)| toughness(c)))
                .unwrap_or(1);
            let name = found.map(|(_, c)| c.name.clone()).unwrap_or_else(|| "an attacker".into());
            let blocked = combat.blocks.iter().any(|b| b.attacker_iid == a.iid);
            Some(Atk { a, card: found.map(|(_, c)| c), power: p, toughness: t, name, blocked })
        })
        .collect();
    if incoming.is_empty() {
        return None;
    }
    incoming.sort_by_key(|x| std::cmp::Reverse(x.power));

    let mut free: Vec<&Card> = me
        .battlefield
        .iter()
        .filter(|c| {
            is_creature(c)
                && !c.tapped
                && !combat.blocks.iter().any(|b| b.blocker_iid == c.iid)
        })
        .collect();
    if free.is_empty() {
        return None;
    }
    free.sort_by_key(|c| std::cmp::Reverse(eval_creature(c)));

    let unblocked_total: i64 = incoming.iter().filter(|x| !x.blocked).map(|x| x.power).sum();
    let danger_threshold = if crate::rooms::format_has_commander(&room.format) { 8 } else { 4 };
    let in_danger = me.life - unblocked_total < danger_threshold;

    // Ward & Cowling race check: healthy and out-racing? Keep everything back
    // for the counterattack instead of trading it away. Defensive bots block
    // anyway; that is their whole personality.
    if !in_danger && style == Style::Aggro {
        let my_power: i64 = me.battlefield.iter().filter(|c| is_creature(c)).map(power).sum();
        if my_power > unblocked_total * 2 {
            return None;
        }
    }

    let enforced_room = crate::rules::enforced(room);
    let pairable = |b: &Card, atk: &Atk, allow_single_menace: bool| -> bool {
        let Some(card) = atk.card else { return true };
        if !block_legal(app, room, b, card) {
            return false;
        }
        if enforced_room && !allow_single_menace {
            let menace = crate::rules::facts(app, card).map(|f| f.has("menace")).unwrap_or(false);
            if menace {
                return false;
            }
        }
        true
    };
    let declare = |blocker: &Card, atk: &Atk, mind: &mut BotMind, say: &mut Vec<String>| {
        if mind.block_says < 2 {
            mind.block_says += 1;
            say.push(block_line(&blocker.name, &atk.name));
        }
        Some(Action::CombatBlock {
            blocker_iid: blocker.iid.clone(),
            attacker_iid: atk.a.iid.clone(),
            power: Some(power(blocker).to_string()),
            toughness: Some(toughness(blocker).to_string()),
        })
    };

    // Pass 1: free blocks. Kill it, keep the blocker.
    for atk in incoming.iter().filter(|x| !x.blocked) {
        for b in &free {
            if atk.toughness > 0
                && power(b) >= atk.toughness
                && toughness(b) > atk.power
                && pairable(b, atk, false)
            {
                return declare(b, atk, mind, say);
            }
        }
    }

    // Pass 2: profitable trades (mutual kill, their creature worth at least
    // ours; the margin collapses as life gets low).
    let margin = if in_danger { -40 } else { 0 };
    for atk in incoming.iter().filter(|x| !x.blocked) {
        let atk_eval = 100 + 15 * atk.power + 10 * atk.toughness;
        for b in free.iter().rev() {
            // Smallest adequate blocker first.
            let kills = atk.toughness > 0 && power(b) >= atk.toughness;
            let dies = atk.power >= toughness(b);
            if kills && dies && atk_eval >= eval_creature(b) + margin && pairable(b, atk, false) {
                return declare(b, atk, mind, say);
            }
        }
    }

    // Pass 3: gang up on the biggest attacker when two blockers finish it.
    if (in_danger || style == Style::Defensive) && tier >= 0 {
        if let Some(atk) = incoming.iter().find(|x| !x.blocked) {
            if free.len() >= 2 && atk.toughness > 0 {
                let combined = power(free[0]) + power(free[1]);
                if combined >= atk.toughness
                    && pairable(free[0], atk, true)
                    && pairable(free[1], atk, true)
                {
                    return declare(free[0], atk, mind, say);
                }
            }
        }
        // Second gang member: an attacker already blocked (by me) but not yet
        // dead to the declared blockers.
        for atk in incoming.iter().filter(|x| x.blocked) {
            let committed: i64 = combat
                .blocks
                .iter()
                .filter(|b| b.attacker_iid == atk.a.iid)
                .filter_map(|b| stat(b.power.as_deref()))
                .sum();
            if atk.toughness > 0 && committed < atk.toughness {
                if let Some(b) = free
                    .iter()
                    .find(|b| committed + power(b) >= atk.toughness && pairable(b, atk, true))
                {
                    return declare(b, atk, mind, say);
                }
            }
        }
    }

    // Pass 4: chump blocks, only when the unblocked damage would actually
    // put me in the red. Cheapest creature onto the biggest attacker.
    if in_danger && tier >= 0 {
        for atk in incoming.iter().filter(|x| !x.blocked) {
            if let Some(b) = free.iter().rev().find(|b| pairable(b, atk, false)) {
                return declare(b, atk, mind, say);
            }
        }
    }
    None
}

// ---------------------------------------------------------- combat: attacks

/// Threat score for an opponent (recomputed every combat so the bot never
/// tunnels on one player): board value + resources + a finisher bonus for low
/// life, discounted by how well-defended they are. Jittered so a table of
/// bots does not dogpile identically.
fn threat_score(p: &Player, starting_life: i64) -> i64 {
    let board: i64 = p.battlefield.iter().filter(|c| is_creature(c)).map(eval_creature).sum();
    let permanents = p.battlefield.len() as i64;
    let above_start = if p.life > starting_life { 20 } else { 0 };
    let kill_bonus = if p.life < 20 { (20 - p.life) * (20 - p.life) } else { 0 };
    let resistance: i64 = p
        .battlefield
        .iter()
        .filter(|c| is_creature(c) && !c.tapped)
        .map(toughness)
        .sum();
    let base = board + 10 * permanents + above_start + kill_bonus - resistance;
    // +-10% jitter.
    let jitter = base / 10;
    if jitter > 0 {
        base + rand::random_range(-jitter..=jitter)
    } else {
        base
    }
}

/// Race math on the Forge ladder: how the boards clock each other, folded
/// into the style's baseline aggression. Only creatures the bot can actually
/// read (attrs or declared stats) count; a human's unknown cards read as 0,
/// which biases bots toward attacking humans - acceptable for a freeform
/// table where the human settles their own defense.
fn aggression(room: &Room, me: &Player, defender: &Player, style: Style) -> i32 {
    let my_dmg: i64 = me.battlefield.iter().filter(|c| is_creature(c)).map(power).sum::<i64>().max(1);
    let incoming: i64 = room
        .players
        .iter()
        .filter(|p| p.seat != me.seat && !p.conceded)
        .flat_map(|p| p.battlefield.iter())
        .filter(|c| is_creature(c))
        .map(power)
        .sum();
    let my_turns_to_die = me.life / incoming.max(1);
    let their_turns_to_die = defender.life / my_dmg;
    let mut level = base_aggression(style);
    if my_turns_to_die > their_turns_to_die {
        level += 1;
    } else if my_turns_to_die < their_turns_to_die {
        level -= 1;
    }
    // Lethal on the board: alpha strike, no holding back.
    let untapped_power: i64 = me
        .battlefield
        .iter()
        .filter(|c| is_creature(c) && !c.tapped)
        .map(power)
        .sum();
    let absorb: i64 =
        defender.battlefield.iter().filter(|c| is_creature(c) && !c.tapped).count() as i64 * 2;
    if untapped_power >= defender.life + absorb {
        level = 5;
    }
    level.clamp(0, 5)
}

/// Pick who to attack: lethal target first, then the archenemy rule, then the
/// best threat-vs-resistance score.
fn pick_target<'a>(room: &'a Room, me: &Player) -> Option<&'a Player> {
    let starting_life = room
        .settings
        .starting_life
        .unwrap_or_else(|| crate::rooms::format_default_life(&room.format));
    let opps: Vec<&Player> =
        room.players.iter().filter(|p| p.seat != me.seat && !p.conceded).collect();
    if opps.is_empty() {
        return None;
    }
    // Lethal check: my untapped power vs their life and untapped defense.
    let untapped_power: i64 = me
        .battlefield
        .iter()
        .filter(|c| is_creature(c) && !c.tapped)
        .map(power)
        .sum();
    if let Some(&dead) = opps
        .iter()
        .filter(|p| {
            let blockers = p.battlefield.iter().filter(|c| is_creature(c) && !c.tapped).count();
            untapped_power >= p.life + 2 * blockers as i64
        })
        .min_by_key(|p| p.life)
    {
        return Some(dead);
    }
    let mut scored: Vec<(i64, &Player)> =
        opps.iter().map(|p| (threat_score(p, starting_life), *p)).collect();
    scored.sort_by_key(|(s, _)| std::cmp::Reverse(*s));
    // Archenemy rule: a runaway leader eats every attack.
    if scored.len() >= 2 && scored[0].0 > scored[1].0 + scored[1].0 / 2 {
        return Some(scored[0].1);
    }
    Some(scored[0].1)
}

/// Build this turn's attack: who to hit and with what. None = stay home.
fn plan_attack(app: &App, room: &Room, me: &Player, mind: &BotMind, style: Style, tier: i32) -> Option<AttackPlan> {
    let defender = pick_target(room, me)?;
    let level = (aggression(room, me, defender, style) + tier).clamp(0, 5);
    if level <= 0 {
        return None;
    }
    let their_blockers: Vec<&Card> = defender
        .battlefield
        .iter()
        .filter(|c| is_creature(c) && !c.tapped)
        .collect();

    let mut ready: Vec<&Card> = me
        .battlefield
        .iter()
        .filter(|c| {
            is_creature(c)
                && !c.tapped
                && power(c) > 0
                && !mind.played_this_turn.iter().any(|iid| iid == &c.iid)
                && attack_legal(app, room, c)
        })
        .collect();
    if ready.is_empty() {
        return None;
    }
    ready.sort_by_key(|c| std::cmp::Reverse(power(c)));

    // Per-creature safety classes (Forge): unblockable-ish always goes; safe
    // attackers from level 1; even trades from level 3; sacrifices only at 5.
    let mut chosen: Vec<&Card> = Vec::new();
    for &c in &ready {
        let class = if their_blockers.is_empty() {
            0 // nothing can block: free damage
        } else {
            let mut killed_by_any = false;
            let mut all_trade_back = true;
            for &b in &their_blockers {
                if toughness(c) > 0 && power(b) >= toughness(c) {
                    killed_by_any = true;
                    if !(toughness(b) > 0 && power(c) >= toughness(b)) {
                        all_trade_back = false;
                    }
                }
            }
            if !killed_by_any {
                1 // safe: survives anything they can put in front
            } else if all_trade_back {
                3 // trades at worst
            } else {
                5 // dies for free to something
            }
        };
        if level >= class {
            chosen.push(c);
        }
    }
    if chosen.is_empty() {
        return None;
    }

    // Hold back a defender when a THIRD party still threatens me at home
    // (never when alpha-striking).
    if level < 5 {
        let outside_threat = room
            .players
            .iter()
            .filter(|p| p.seat != me.seat && p.seat != defender.seat && !p.conceded)
            .flat_map(|p| p.battlefield.iter())
            .any(|c| is_creature(c) && power(c) >= 2);
        let hold = if outside_threat {
            if style == Style::Defensive {
                2
            } else {
                1
            }
        } else {
            0
        };
        for _ in 0..hold {
            if chosen.len() <= 1 {
                break;
            }
            // Keep home the best blocker: highest toughness.
            let (idx, _) = chosen
                .iter()
                .enumerate()
                .max_by_key(|(_, c)| toughness(c))
                .unwrap();
            chosen.remove(idx);
        }
    }
    if chosen.is_empty() {
        return None;
    }

    Some(AttackPlan {
        defender_seat: defender.seat,
        pending: chosen.iter().rev().map(|c| c.iid.clone()).collect(),
        announced: false,
        announced_at: 0,
        defender_life: 0,
        blocks_seen: 0,
        respond_grace_until: 0,
        needs_lock: false,
    })
}

// ----------------------------------------------------------------- own turn

/// The bot's own turn: resolve its stack spells, drop a land, cast what the
/// untapped lands afford, run the attack plan, wrap combat, pass. Never
/// stalls past the failsafe.
fn own_turn(app: &App, room: &Room, me: &Player, mind: &mut BotMind, style: Style, now: i64) -> Decision {
    let tn = room.turn_number;
    if mind.turn_started.map(|(t, _)| t) != Some(tn) {
        mind.turn_started = Some((tn, now));
        mind.casting = None;
        mind.attack = None;
        mind.played_this_turn.clear();
        // Every fresh turn gets a beat of "thinking" before the first move.
        return Decision::none();
    }
    // The beat is a real minimum, not just a skipped tick: whatever the
    // scheduler cadence, a turn's first action waits TURN_MIN_THINK_MS.
    if now - mind.turn_started.map(|(_, ts)| ts).unwrap_or(now) < TURN_MIN_THINK_MS {
        return Decision::none();
    }
    if mind.casts.0 != tn {
        mind.casts = (tn, 0);
    }
    // The turn failsafe, EXCEPT while an announced attack is holding the
    // response window open - that clock belongs to the defender and is
    // bounded by its own cap.
    let awaiting_response = mind.attack.as_ref().map(|p| p.announced).unwrap_or(false);
    if !awaiting_response
        && now - mind.turn_started.map(|(_, ts)| ts).unwrap_or(now) > TURN_FAILSAFE_MS
    {
        mind.casting = None;
        mind.attack = None;
        if room.combat.is_some() {
            return Decision::act(Action::CombatEnd);
        }
        return Decision::act(Action::TurnPass);
    }
    // Spells the bot pushed ride the stack one tick, then hit the graveyard.
    // (Enforced rooms handled this earlier in decide(), passes included.)
    if !crate::rules::enforced(room) {
        if let Some(entry) = room.stack.iter().find(|e| e.owner == me.user_id) {
            return Decision::act(Action::StackResolve {
                iid: entry.card.iid.clone(),
                to: Zone::Graveyard,
                x: None,
                y: None,
            });
        }
    }

    // Mid-combat: declare the next attacker, announce, wait, then wrap.
    if let Some(combat) = &room.combat {
        let explicit_defender = room.players.len() > 2;
        if let Some(plan) = &mut mind.attack {
            if let Some(iid) = plan.pending.pop() {
                let card = me.battlefield.iter().find(|c| c.iid == iid);
                let Some(card) = card else {
                    return Decision::none();
                };
                return Decision::act(Action::CombatAttack {
                    iid,
                    defender_seat: explicit_defender.then_some(plan.defender_seat),
                    power: Some(power(card).to_string()),
                    toughness: Some(toughness(card).to_string()),
                });
            }
            if !plan.announced {
                plan.announced = true;
                plan.announced_at = now;
                plan.blocks_seen = combat.blocks.len();
                plan.needs_lock = crate::rules::enforced(room);
                plan.defender_life = room
                    .players
                    .iter()
                    .find(|p| p.seat == plan.defender_seat)
                    .map(|p| p.life)
                    .unwrap_or(0);
                // Announce from what actually got declared.
                let mut total = 0i64;
                let mut names: Vec<String> = Vec::new();
                for a in &combat.attackers {
                    if let Some(c) = me.battlefield.iter().find(|c| c.iid == a.iid) {
                        total += stat(a.power.as_deref()).unwrap_or_else(|| power(c));
                        names.push(c.name.clone());
                    }
                }
                let defender_name = room
                    .players
                    .iter()
                    .find(|p| p.seat == plan.defender_seat)
                    .map(|p| p.username.clone())
                    .unwrap_or_else(|| "the table".to_string());
                if !names.is_empty() {
                    // Enforced rooms pair the announcement with the lock-in.
                    let action = plan.needs_lock.then_some(Action::CombatLock);
                    plan.needs_lock = false;
                    return Decision {
                        action,
                        say: vec![attack_line(&defender_name, total, &names)],
                        fast: false,
                    };
                }
                if plan.needs_lock {
                    plan.needs_lock = false;
                    return Decision::act(Action::CombatLock);
                }
                return Decision::none();
            }
            if crate::rules::enforced(room) {
                // Enforced machine: wait for the defender's Ready (the server
                // computed the preview), give the table a beat to read it,
                // then resolve. A silent defender caps out and the attack is
                // withdrawn rather than force-resolved.
                if combat.preview.is_some() {
                    if now - plan.announced_at < 1_200 {
                        return Decision::none();
                    }
                    mind.attack = None;
                    return Decision::act(Action::CombatResolve);
                }
                let humans_defending = room
                    .players
                    .iter()
                    .any(|p| !p.is_bot && !p.conceded && p.seat != me.seat);
                let cap = if humans_defending { ATTACK_WAIT_HUMAN_MAX_MS } else { 6_000 };
                if now - plan.announced_at >= cap {
                    mind.attack = None;
                    return Decision::act(Action::CombatEnd);
                }
                return Decision::none();
            }
            // The response window. All-bot tables move on almost at once;
            // against humans the combat stays open until the defender has
            // actually answered, up to a generous cap. The defender can
            // always cut this short with their own End combat / Take damage.
            let humans_defending = room
                .players
                .iter()
                .any(|p| !p.is_bot && !p.conceded && p.seat != me.seat);
            let watched = !room.spectators.is_empty();
            if !humans_defending {
                if now - plan.announced_at < if watched { 4_000 } else { ATTACK_WAIT_BOTS_MS } {
                    return Decision::none();
                }
                mind.attack = None;
                return Decision::act(Action::CombatEnd);
            }
            // New blocks reset the grace window: they are still deciding.
            if combat.blocks.len() != plan.blocks_seen {
                plan.blocks_seen = combat.blocks.len();
                plan.respond_grace_until = now + ATTACK_RESPONSE_GRACE_MS;
                return Decision::none();
            }
            // The defender settled the damage on their own life: nearly done,
            // give them a beat and wrap.
            let defender_life_now = room
                .players
                .iter()
                .find(|p| p.seat == plan.defender_seat)
                .map(|p| p.life)
                .unwrap_or(plan.defender_life);
            if defender_life_now < plan.defender_life && plan.respond_grace_until == 0 {
                plan.respond_grace_until = now + 1_500;
                return Decision::none();
            }
            let responded = plan.respond_grace_until > 0;
            if responded && now >= plan.respond_grace_until {
                mind.attack = None;
                return Decision::act(Action::CombatEnd);
            }
            if now - plan.announced_at >= ATTACK_WAIT_HUMAN_MAX_MS {
                mind.attack = None;
                return Decision::act(Action::CombatEnd);
            }
            return Decision::none();
        }
        // Combat overlay without a plan (restart, or someone else opened it
        // on our turn): just close it out.
        return Decision::act(Action::CombatEnd);
    }

    let tier = tier_of(me);
    match room.phase.as_str() {
        "main2" | "end" => {
            // Post-combat: maybe one more spell from the budget, then pass.
            if let Some(d) = cast_step(app, room, me, mind, style, tier, tn) {
                return d;
            }
            Decision::act(Action::TurnPass)
        }
        _ => {
            // First main phase: land, spells, then combat when the style
            // likes an attack.
            if mind.land_turn != Some(tn) {
                mind.land_turn = Some(tn);
                if let Some(land) = me.hand.iter().find(|c| is_land(c)) {
                    let n = me.battlefield.iter().filter(|c| is_land(c)).count();
                    return Decision::act(Action::CardMove {
                        iid: land.iid.clone(),
                        to: Zone::Battlefield,
                        x: Some((0.05 + 0.085 * (n % 11) as f64).min(0.95)),
                        y: Some(0.78),
                        index: None,
                        face_down: false,
                    });
                }
            }
            if let Some(d) = cast_step(app, room, me, mind, style, tier, tn) {
                return d;
            }
            if let Some(plan) = plan_attack(app, room, me, mind, style, tier) {
                mind.attack = Some(plan);
                return Decision::act(Action::CombatBegin);
            }
            Decision::act(Action::TurnPass)
        }
    }
}

// ------------------------------------------------------------------ casting

/// One step of casting per tick: continue paying for the planned spell (tap a
/// land), fire it once paid, or pick a new affordable target. The commander
/// gets priority when the lands cover mana value plus tax. Enforced rooms
/// skip the tap choreography entirely: the Cast action pays server-side with
/// real colors, so the bot just picks the best affordable card.
fn cast_step(app: &App, room: &Room, me: &Player, mind: &mut BotMind, style: Style, tier: i32, tn: u64) -> Option<Decision> {
    let budget = (cast_budget(style) as i32 + tier).max(1) as u32;
    if crate::rules::enforced(room) {
        if mind.casts.1 >= budget {
            return None;
        }
        // Commander first when the real cost plus tax is payable.
        let commander = me.command.iter().filter(|c| c.is_commander).find(|c| {
            crate::rules::facts(app, c)
                .map(|f| {
                    let tax = me.commander_tax.get(&c.iid).copied().unwrap_or(0);
                    crate::rules::can_afford(
                        app,
                        me,
                        crate::rules::reduced_generic(app, me, &f, f.generic + tax),
                        &f.pips,
                    )
                })
                .unwrap_or(false)
        });
        let k = me.battlefield.iter().filter(|c| !is_land(c)).count();
        let x = (0.15 + 0.11 * (k % 7) as f64).min(0.92);
        let y = 0.5;
        if let Some(c) = commander {
            mind.casts = (tn, mind.casts.1 + 1);
            mind.played_this_turn.push(c.iid.clone());
            return Some(Decision {
                action: Some(Action::CmdCast { iid: c.iid.clone(), x, y }),
                say: vec![commander_line(&c.name)],
                fast: false,
            });
        }
        // Biggest affordable spell, creatures breaking ties.
        let mut best: Option<(&Card, i64, bool)> = None;
        for c in &me.hand {
            let Some(f) = crate::rules::facts(app, c) else { continue };
            if f.is_land()
                || !crate::rules::can_afford(
                    app,
                    me,
                    crate::rules::reduced_generic(app, me, &f, f.generic),
                    &f.pips,
                )
            {
                continue;
            }
            let better = match &best {
                Some((_, mv, creature)) => (f.mv, f.is_creature()) > (*mv, *creature),
                None => true,
            };
            if better {
                best = Some((c, f.mv, f.is_creature()));
            }
        }
        let (card, _, _) = best?;
        mind.casts = (tn, mind.casts.1 + 1);
        mind.played_this_turn.push(card.iid.clone());
        return Some(Decision::act(Action::Cast {
            iid: card.iid.clone(),
            payment: None,
            x: Some(x),
            y: Some(y),
        }));
    }
    if let Some(d) = plan_step(me, mind, tn) {
        return Some(d);
    }
    if mind.casts.1 >= budget {
        return None;
    }
    let untapped: Vec<String> = me
        .battlefield
        .iter()
        .filter(|c| is_land(c) && !c.tapped)
        .map(|c| c.iid.clone())
        .collect();
    let lands = untapped.len() as i64;
    let commander = me.command.iter().filter(|c| c.is_commander).find_map(|c| {
        let cost = mana_value(c) + me.commander_tax.get(&c.iid).copied().unwrap_or(0);
        (cost <= lands).then(|| CastPlan {
            iid: c.iid.clone(),
            from_command: true,
            taps: Vec::new(),
            to_stack: false,
            announce: Some(commander_line(&c.name)),
        })
        .map(|p| (p, cost))
    });
    let target = commander.or_else(|| {
        me.hand
            .iter()
            .filter(|c| attr(c).is_some() && !is_land(c) && mana_value(c) <= lands)
            .max_by_key(|c| (mana_value(c), is_creature(c)))
            .map(|c| {
                (
                    CastPlan {
                        iid: c.iid.clone(),
                        from_command: false,
                        taps: Vec::new(),
                        to_stack: is_spell(c),
                        announce: None,
                    },
                    mana_value(c),
                )
            })
    });
    let (mut plan, cost) = target?;
    plan.taps = untapped.into_iter().take(cost.max(0) as usize).collect();
    mind.casting = Some(plan);
    plan_step(me, mind, tn)
}

/// Execute one step of the current cast plan; clears plans whose card left
/// its zone (self-healing after restarts or interference).
fn plan_step(me: &Player, mind: &mut BotMind, tn: u64) -> Option<Decision> {
    let mut clear = false;
    let mut tap: Option<String> = None;
    if let Some(plan) = &mut mind.casting {
        let still_there = if plan.from_command {
            me.command.iter().any(|c| c.iid == plan.iid)
        } else {
            me.hand.iter().any(|c| c.iid == plan.iid)
        };
        if !still_there {
            clear = true;
        } else {
            while let Some(land) = plan.taps.pop() {
                if me.battlefield.iter().any(|c| c.iid == land && !c.tapped) {
                    tap = Some(land);
                    break;
                }
            }
        }
    }
    if clear {
        mind.casting = None;
        return None;
    }
    if let Some(iid) = tap {
        return Some(Decision::fast(Action::CardTap { iid, tapped: true, mana: None }));
    }
    let plan = mind.casting.take()?;
    mind.casts = (tn, mind.casts.1 + 1);
    let say = plan.announce.map(|l| vec![l]).unwrap_or_default();
    let k = me.battlefield.iter().filter(|c| !is_land(c)).count();
    let x = (0.15 + 0.11 * (k % 7) as f64).min(0.92);
    let y = 0.5;
    mind.played_this_turn.push(plan.iid.clone());
    let action = if plan.from_command {
        Action::CmdCast { iid: plan.iid, x, y }
    } else if plan.to_stack {
        Action::StackPush { iid: plan.iid }
    } else {
        Action::CardMove {
            iid: plan.iid,
            to: Zone::Battlefield,
            x: Some(x),
            y: Some(y),
            index: None,
            face_down: false,
        }
    };
    Some(Decision { action: Some(action), say, fast: false })
}
