//! Server-resident AI opponents (PROTOCOL.md, Bots addendum v2.1).
//!
//! A bot is an ordinary `Player` driven by one scheduler task. Every act goes
//! through `ws::dispatch_action`, the identical pipeline human actions use, so
//! bots obey the same freeform contract: the server records, never judges.
//!
//! The scheduler is stateless across restarts: rooms are persisted and
//! reloaded, and scanning them resumes every bot automatically. Per-bot
//! scratch memory (`BotMind`) lives only in this task and self-heals from
//! room state when missing.

use crate::game::{Action, Zone};
use crate::rooms::{Card, Combat, Player, Room};
use crate::{ws, App};
use serde::Deserialize;
use std::collections::{HashMap, VecDeque};
use std::sync::{Arc, OnceLock};
use std::time::Duration;

// ------------------------------------------------------------ embedded data

/// Generated by scripts/gen-bot-data.mjs from src/data/precons.json.
#[derive(Deserialize)]
pub struct BotData {
    pub decks: Vec<BotDeck>,
    pub attrs: HashMap<String, CardAttr>,
}

#[derive(Deserialize)]
pub struct BotDeck {
    pub code: String,
    #[allow(dead_code)]
    pub name: String,
    pub cards: Vec<BotDeckCard>,
}

#[derive(Deserialize)]
pub struct BotDeckCard {
    pub sid: String,
    pub name: String,
    pub qty: u32,
    pub board: String,
}

/// Per-card attributes: mana value, type letters (subset of LCISAEPB, O =
/// other), and printed power/toughness when present.
#[derive(Deserialize)]
pub struct CardAttr {
    pub mv: f64,
    pub t: String,
    #[serde(default)]
    pub p: Option<String>,
    #[serde(default)]
    pub tg: Option<String>,
}

static DATA: OnceLock<BotData> = OnceLock::new();

pub fn data() -> &'static BotData {
    DATA.get_or_init(|| {
        serde_json::from_str(include_str!("data/bot_data.json")).expect("bot_data.json parses")
    })
}

const PERSONAS: [&str; 6] = ["Aster", "Bramble", "Cirrus", "Moss", "Quill", "Wren"];

/// An unused persona username for this room ("Aster (AI)"); numbered fallback
/// if the pool is somehow exhausted.
pub fn pick_name(room: &Room) -> String {
    let start = rand::random_range(0..PERSONAS.len());
    for i in 0..PERSONAS.len() {
        let name = format!("{} (AI)", PERSONAS[(start + i) % PERSONAS.len()]);
        if !room.players.iter().any(|p| p.username == name) {
            return name;
        }
    }
    format!("{} {} (AI)", PERSONAS[start], crate::hex_id(2))
}

// ------------------------------------------------------------ card reading

fn attr(card: &Card) -> Option<&'static CardAttr> {
    card.scryfall_id.as_deref().and_then(|sid| data().attrs.get(sid))
}

fn is_land(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('L')).unwrap_or(false)
}

fn is_creature(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('C')).unwrap_or(false) || card.power.is_some()
}

fn mana_value(card: &Card) -> i64 {
    attr(card).map(|a| a.mv.round() as i64).unwrap_or(0)
}

fn stat(s: Option<&str>) -> Option<i64> {
    s.and_then(|v| v.trim().parse::<i64>().ok())
}

fn power(card: &Card) -> i64 {
    stat(card.power.as_deref())
        .or_else(|| attr(card).and_then(|a| stat(a.p.as_deref())))
        .unwrap_or(0)
}

fn toughness(card: &Card) -> i64 {
    stat(card.toughness.as_deref())
        .or_else(|| attr(card).and_then(|a| stat(a.tg.as_deref())))
        .unwrap_or(0)
}

// ------------------------------------------------------------------- style

#[derive(Clone, Copy, PartialEq)]
enum Style {
    Casual,
    Aggro,
    Defensive,
}

fn style_of(p: &Player) -> Style {
    match p.bot_style.as_deref() {
        Some("aggro") => Style::Aggro,
        Some("defensive") => Style::Defensive,
        _ => Style::Casual,
    }
}

/// Spells the bot is willing to cast in one of its turns.
fn cast_budget(style: Style) -> u32 {
    match style {
        Style::Casual => 2,
        Style::Aggro => 3,
        Style::Defensive => 2,
    }
}

// -------------------------------------------------------------------- mind

/// Payment in progress: tap `taps` one per tick, then fire the spell.
struct CastPlan {
    iid: String,
    from_command: bool,
    taps: Vec<String>,
    to_stack: bool,
}

struct SnapAttacker {
    iid: String,
    owner_seat: usize,
    power: i64,
    is_commander: bool,
    defender_seat: Option<usize>,
}

/// The last combat this bot defended, kept so damage can be settled once the
/// attacker ends combat (or the turn changes and clears it).
struct CombatSnap {
    attackers: Vec<SnapAttacker>,
    blocks: Vec<(String, String)>, // (blocker iid, attacker iid)
}

/// In-memory scratch for one bot. Never persisted; everything here self-heals
/// from room state (worst case after a restart: an extra land drop or a
/// forgotten damage bookkeeping entry).
#[derive(Default)]
struct BotMind {
    /// Bookkeeping actions queued for later ticks (post-combat life, ...).
    queue: VecDeque<Action>,
    /// (turn round, unix ms) when this bot's actionable turn began.
    turn_started: Option<(u64, i64)>,
    /// Turn round the bot last played a land in (or gave up looking).
    land_turn: Option<u64>,
    /// (turn round, spells cast so far that round).
    casts: (u64, u32),
    casting: Option<CastPlan>,
    /// Live snapshot of a combat this bot is defending (block bookkeeping).
    last_combat: Option<CombatSnap>,
    /// seq of the last ended combat this bot settled (idempotent, from
    /// room.last_combat). A fresh mind adopts the current marker instead of
    /// settling history (restart safety).
    settled_combat: Option<u64>,
    adopted: bool,
}

const TURN_FAILSAFE_MS: i64 = 25_000;

// --------------------------------------------------------------- scheduler

/// One task for the whole server: every ~800ms, give each bot in each room at
/// most one action. Room ids are collected first and each room is locked on
/// its own; no DashMap ref is ever held across an await.
pub async fn scheduler(app: Arc<App>) {
    let mut minds: HashMap<(String, String), BotMind> = HashMap::new();
    let mut interval = tokio::time::interval(Duration::from_millis(800));
    interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
    loop {
        interval.tick().await;
        let room_ids: Vec<String> = app
            .rooms
            .iter()
            .filter(|r| r.players.iter().any(|p| p.is_bot))
            .map(|r| r.id.clone())
            .collect();
        for rid in &room_ids {
            let Some(mut room) = app.rooms.get_mut(rid) else {
                continue;
            };
            let bots: Vec<String> = room
                .players
                .iter()
                .filter(|p| p.is_bot)
                .map(|p| p.user_id.clone())
                .collect();
            for uid in bots {
                let mind = minds.entry((rid.clone(), uid.clone())).or_default();
                if !mind.adopted {
                    // A brand-new mind (boot/restart) must not re-settle a
                    // combat that ended before it existed.
                    mind.adopted = true;
                    mind.settled_combat = room.last_combat.as_ref().map(|c| c.seq);
                }
                let Some(action) = decide(&room, &uid, mind, crate::now_ms()) else {
                    continue;
                };
                if let Err((code, msg)) = ws::dispatch_action(&app, &mut room, &uid, action, None) {
                    eprintln!("bot {uid} in room {rid}: {code}: {msg}");
                }
            }
        }
        // Drop scratch for bots or rooms that no longer exist.
        minds.retain(|(rid, uid), _| {
            app.rooms
                .get(rid)
                .map(|r| r.players.iter().any(|p| p.user_id == *uid))
                .unwrap_or(false)
        });
    }
}

// -------------------------------------------------------------------- brain

/// The bot's one action for this tick, or None to sit still.
fn decide(room: &Room, uid: &str, mind: &mut BotMind, now: i64) -> Option<Action> {
    let me = room.players.iter().find(|p| p.user_id == uid)?;
    if !room.started || room.match_result.is_some() {
        return None;
    }
    let style = style_of(me);

    // A combat that ended (combat.end, or cleared by a turn change) settles
    // its damage against this bot from the room's authoritative record; a
    // fast attack sequence can begin and end entirely between two ticks, so
    // the bot's own live snapshot cannot be trusted to exist.
    if room.combat.is_none() {
        mind.last_combat = None;
        if let Some(ended) = &room.last_combat {
            if mind.settled_combat != Some(ended.seq) {
                mind.settled_combat = Some(ended.seq);
                let snap = snapshot(room, &ended.combat);
                queue_combat_damage(me, &snap, &mut mind.queue);
            }
        }
    }
    if let Some(a) = mind.queue.pop_front() {
        return Some(a);
    }

    // Own mulligan first; it blocks everything else this bot might do.
    if let Some(m) = &me.mulligan {
        if m.state == "deciding" {
            return Some(mulligan_action(room, me, m.taken));
        }
    }

    // Commander headed off the battlefield: always accept the command zone.
    if let Some(p) = room.pending_cmd.iter().find(|p| p.owner == uid) {
        return Some(Action::CmdReturn { iid: p.iid.clone(), accept: true });
    }

    // Wait politely while anyone is still deciding their mulligan. Conceded
    // seats never keep (their decision is void), so they do not hold this up.
    let all_kept = room
        .players
        .iter()
        .filter(|p| !p.conceded)
        .all(|p| p.mulligan.as_ref().map(|m| m.state == "kept").unwrap_or(true));
    if !all_kept {
        return None;
    }

    // Someone else's combat. LOCKED combats (Combat v3) resolve server-side:
    // never snapshot them for the legacy settle; instead declare any blocks,
    // then signal ready. Un-locked combats keep the legacy snapshot flow.
    if let Some(combat) = &room.combat {
        if room.active_seat != me.seat {
            if combat.locked {
                mind.last_combat = None;
                let targeted = combat
                    .attackers
                    .iter()
                    .any(|a| a.defender_seat.map_or(true, |d| d == me.seat));
                if targeted && !combat.ready.contains(&me.seat) {
                    if let Some(a) = choose_block(room, me, combat, style) {
                        return Some(a);
                    }
                    return Some(Action::CombatReady { prevent: None });
                }
                return None;
            }
            mind.last_combat = Some(snapshot(room, combat));
            return choose_block(room, me, combat, style);
        }
    }

    if room.active_seat != me.seat {
        return None;
    }
    own_turn(room, me, mind, style, now)
}

/// Keep any hand with 2-5 lands; otherwise mulligan once, then keep and
/// bottom the owed count (highest mana values first, holding on to two lands
/// where possible).
fn mulligan_action(room: &Room, me: &Player, taken: u32) -> Action {
    let lands = me.hand.iter().filter(|c| is_land(c)).count();
    if !(2..=5).contains(&lands) && taken == 0 {
        return Action::MullTake;
    }
    let free = if room.format == "commander" && room.players.len() >= 3 { 1 } else { 0 };
    let owed = taken.saturating_sub(free) as usize;
    let mut ranked: Vec<(u8, i64, String)> = Vec::new();
    let mut lands_seen = 0u32;
    for c in &me.hand {
        if is_land(c) {
            lands_seen += 1;
            // The first two lands are bottomed only as a last resort.
            let tier = if lands_seen <= 2 { 2 } else { 1 };
            ranked.push((tier, 0, c.iid.clone()));
        } else {
            ranked.push((0, -mana_value(c), c.iid.clone()));
        }
    }
    ranked.sort();
    let bottom_iids = ranked.into_iter().take(owed).map(|(_, _, iid)| iid).collect();
    Action::MullKeep { bottom_iids }
}

fn snapshot(room: &Room, combat: &Combat) -> CombatSnap {
    let attackers = combat
        .attackers
        .iter()
        .filter_map(|a| {
            room.players.iter().find_map(|p| {
                p.battlefield.iter().find(|c| c.iid == a.iid).map(|c| SnapAttacker {
                    iid: a.iid.clone(),
                    owner_seat: p.seat,
                    power: power(c),
                    is_commander: c.is_commander,
                    defender_seat: a.defender_seat,
                })
            })
        })
        .collect();
    let blocks = combat
        .blocks
        .iter()
        .map(|b| (b.blocker_iid.clone(), b.attacker_iid.clone()))
        .collect();
    CombatSnap { attackers, blocks }
}

/// After the attacker ends combat: the bot applies unblocked damage aimed at
/// it to its own life, plus commander-damage bookkeeping. It never touches
/// anyone else's totals.
fn queue_combat_damage(me: &Player, snap: &CombatSnap, queue: &mut VecDeque<Action>) {
    let mut total = 0i64;
    for atk in &snap.attackers {
        if atk.owner_seat == me.seat {
            continue;
        }
        // An attacker targets this bot when aimed at its seat, or aimed at
        // nobody in particular (2-player rooms and open swings).
        if !atk.defender_seat.map_or(true, |d| d == me.seat) {
            continue;
        }
        if snap.blocks.iter().any(|(_, a)| a == &atk.iid) {
            continue;
        }
        if atk.power <= 0 {
            continue;
        }
        total += atk.power;
        if atk.is_commander {
            queue.push_back(Action::CmdDamage {
                from_seat: atk.owner_seat,
                delta: atk.power,
                commander_iid: Some(atk.iid.clone()),
            });
        }
    }
    if total > 0 {
        queue.push_front(Action::LifeAdd { delta: -total });
    }
}

/// One block declaration per tick: largest unblocked attacker gets the
/// largest willing blocker, style-weighted.
fn choose_block(room: &Room, me: &Player, combat: &Combat, style: Style) -> Option<Action> {
    let mut attackers: Vec<&Card> = Vec::new();
    for a in &combat.attackers {
        if !a.defender_seat.map_or(true, |d| d == me.seat) {
            continue;
        }
        if combat.blocks.iter().any(|b| b.attacker_iid == a.iid) {
            continue;
        }
        let found = room.players.iter().find_map(|p| {
            p.battlefield
                .iter()
                .find(|c| c.iid == a.iid)
                .map(|c| (p.seat, c))
        });
        let Some((owner_seat, card)) = found else {
            continue;
        };
        if owner_seat == me.seat {
            continue;
        }
        attackers.push(card);
    }
    attackers.sort_by_key(|c| std::cmp::Reverse(power(c)));
    let mut blockers: Vec<&Card> = me
        .battlefield
        .iter()
        .filter(|c| {
            is_creature(c) && !c.tapped && !combat.blocks.iter().any(|b| b.blocker_iid == c.iid)
        })
        .collect();
    blockers.sort_by_key(|c| std::cmp::Reverse(power(c)));
    for atk in &attackers {
        for b in &blockers {
            if block_ok(style, b, atk) {
                return Some(declare_block(b, atk));
            }
        }
    }
    // Defensive keeps chump-blocking after the favorable options run out.
    if style == Style::Defensive {
        if let (Some(atk), Some(b)) = (attackers.first(), blockers.first()) {
            return Some(declare_block(b, atk));
        }
    }
    None
}

/// A block declaration carrying the blocker's attrs-derived effective stats
/// (Combat v3; bots do not track counters, base values are fine).
fn declare_block(blocker: &Card, attacker: &Card) -> Action {
    Action::CombatBlock {
        blocker_iid: blocker.iid.clone(),
        attacker_iid: attacker.iid.clone(),
        power: Some(power(blocker).to_string()),
        toughness: Some(toughness(blocker).to_string()),
    }
}

fn block_ok(style: Style, blocker: &Card, attacker: &Card) -> bool {
    let kills = toughness(attacker) > 0 && power(blocker) >= toughness(attacker);
    let survives = toughness(blocker) > power(attacker);
    match style {
        Style::Aggro => kills && survives,
        Style::Casual | Style::Defensive => kills || survives,
    }
}

/// The bot's own turn: resolve its stack spells, drop a land, cast what the
/// untapped lands afford, attack per style, wrap combat, pass. Never stalls
/// past the 25s failsafe.
fn own_turn(room: &Room, me: &Player, mind: &mut BotMind, style: Style, now: i64) -> Option<Action> {
    let tn = room.turn_number;
    if mind.turn_started.map(|(t, _)| t) != Some(tn) {
        mind.turn_started = Some((tn, now));
        mind.casting = None;
    }
    if mind.casts.0 != tn {
        mind.casts = (tn, 0);
    }
    if now - mind.turn_started.map(|(_, ts)| ts).unwrap_or(now) > TURN_FAILSAFE_MS {
        mind.casting = None;
        return Some(Action::TurnPass);
    }
    // Spells the bot pushed ride the stack one tick, then hit the graveyard.
    if let Some(entry) = room.stack.iter().find(|e| e.owner == me.user_id) {
        return Some(Action::StackResolve {
            iid: entry.card.iid.clone(),
            to: Zone::Graveyard,
            x: None,
            y: None,
        });
    }
    // Mid-combat: declare the next attacker, or wrap up.
    if room.combat.is_some() {
        return Some(next_attack(room, me, style).unwrap_or(Action::CombatEnd));
    }
    match room.phase.as_str() {
        "main2" | "end" => {
            // Post-combat: maybe one more spell from the budget, then pass.
            if let Some(a) = cast_step(me, mind, style, tn) {
                return Some(a);
            }
            Some(Action::TurnPass)
        }
        _ => {
            // First main phase (and any odd pre-combat phase): land, spells,
            // then combat when the style likes an attack.
            if mind.land_turn != Some(tn) {
                mind.land_turn = Some(tn);
                if let Some(land) = me.hand.iter().find(|c| is_land(c)) {
                    let n = me.battlefield.iter().filter(|c| is_land(c)).count();
                    return Some(Action::CardMove {
                        iid: land.iid.clone(),
                        to: Zone::Battlefield,
                        x: Some((0.05 + 0.085 * (n % 11) as f64).min(0.95)),
                        y: Some(0.78),
                        index: None,
                    });
                }
            }
            if let Some(a) = cast_step(me, mind, style, tn) {
                return Some(a);
            }
            if next_attack(room, me, style).is_some() {
                return Some(Action::CombatBegin);
            }
            Some(Action::TurnPass)
        }
    }
}

/// The next creature this style wants to send in (not yet declared), aimed at
/// the lowest-life opponent (explicit defenderSeat only in 3+ player rooms).
/// None means combat is over (or never worth beginning).
fn next_attack(room: &Room, me: &Player, style: Style) -> Option<Action> {
    let declared: Vec<&str> = room
        .combat
        .as_ref()
        .map(|c| c.attackers.iter().map(|a| a.iid.as_str()).collect())
        .unwrap_or_default();
    let mut ready: Vec<&Card> = me
        .battlefield
        .iter()
        .filter(|c| is_creature(c) && !c.tapped && !declared.contains(&c.iid.as_str()))
        .collect();
    if ready.is_empty() {
        return None;
    }
    ready.sort_by_key(|c| std::cmp::Reverse(power(c)));
    let defender = room
        .players
        .iter()
        .filter(|p| p.seat != me.seat)
        .min_by_key(|p| p.life)?;
    let best_defense = defender
        .battlefield
        .iter()
        .filter(|c| is_creature(c) && !c.tapped)
        .map(|c| power(c))
        .max();
    let pick: Option<&Card> = match (style, best_defense) {
        (Style::Aggro, _) | (_, None) => ready.first().copied(),
        (Style::Casual, Some(best)) => ready.iter().copied().find(|&c| power(c) >= best),
        (Style::Defensive, Some(_)) => None,
    };
    let card = pick?;
    let defender_seat = (room.players.len() > 2).then_some(defender.seat);
    Some(Action::CombatAttack {
        iid: card.iid.clone(),
        defender_seat,
        power: Some(power(card).to_string()),
        toughness: Some(toughness(card).to_string()),
    })
}

/// One step of casting per tick: continue paying for the planned spell (tap a
/// land), fire it once paid, or pick a new affordable target. The commander
/// gets priority when the lands cover mana value plus tax.
fn cast_step(me: &Player, mind: &mut BotMind, style: Style, tn: u64) -> Option<Action> {
    if let Some(a) = plan_step(me, mind, tn) {
        return Some(a);
    }
    if mind.casts.1 >= cast_budget(style) {
        return None;
    }
    let untapped: Vec<String> = me
        .battlefield
        .iter()
        .filter(|c| is_land(c) && !c.tapped)
        .map(|c| c.iid.clone())
        .collect();
    let lands = untapped.len() as i64;
    let commander = me.command.iter().filter(|c| c.is_commander).find_map(|c| {
        let cost = mana_value(c) + me.commander_tax.get(&c.iid).copied().unwrap_or(0);
        (cost <= lands).then(|| (c.iid.clone(), cost, true, false))
    });
    let target = commander.or_else(|| {
        me.hand
            .iter()
            .filter(|c| attr(c).is_some() && !is_land(c) && mana_value(c) <= lands)
            .max_by_key(|c| mana_value(c))
            .map(|c| {
                let spell = attr(c)
                    .map(|a| a.t.contains('I') || a.t.contains('S'))
                    .unwrap_or(false);
                (c.iid.clone(), mana_value(c), false, spell)
            })
    });
    let (iid, cost, from_command, to_stack) = target?;
    let taps = untapped.into_iter().take(cost.max(0) as usize).collect();
    mind.casting = Some(CastPlan { iid, from_command, taps, to_stack });
    plan_step(me, mind, tn)
}

/// Execute one step of the current cast plan; clears plans whose card left
/// its zone (self-healing after restarts or interference).
fn plan_step(me: &Player, mind: &mut BotMind, tn: u64) -> Option<Action> {
    let mut clear = false;
    let mut tap: Option<String> = None;
    if let Some(plan) = &mut mind.casting {
        let still_there = if plan.from_command {
            me.command.iter().any(|c| c.iid == plan.iid)
        } else {
            me.hand.iter().any(|c| c.iid == plan.iid)
        };
        if !still_there {
            clear = true;
        } else {
            while let Some(land) = plan.taps.pop() {
                if me.battlefield.iter().any(|c| c.iid == land && !c.tapped) {
                    tap = Some(land);
                    break;
                }
            }
        }
    }
    if clear {
        mind.casting = None;
        return None;
    }
    if let Some(iid) = tap {
        return Some(Action::CardTap { iid, tapped: true });
    }
    let plan = mind.casting.take()?;
    mind.casts = (tn, mind.casts.1 + 1);
    let k = me.battlefield.iter().filter(|c| !is_land(c)).count();
    let x = (0.15 + 0.11 * (k % 7) as f64).min(0.92);
    let y = 0.5;
    if plan.from_command {
        return Some(Action::CmdCast { iid: plan.iid, x, y });
    }
    if plan.to_stack {
        return Some(Action::StackPush { iid: plan.iid });
    }
    Some(Action::CardMove {
        iid: plan.iid,
        to: Zone::Battlefield,
        x: Some(x),
        y: Some(y),
        index: None,
    })
}
