//! What the bot can KNOW: the embedded precon data, card attribute reads,
//! creature evaluation, and per-seat style/tier - facts, never decisions.

use super::*;

// ------------------------------------------------------------ embedded data

/// Generated by scripts/gen-bot-data.mjs from src/data/precons.json.
#[derive(Deserialize)]
pub struct BotData {
    pub decks: Vec<BotDeck>,
    pub attrs: HashMap<String, CardAttr>,
}

#[derive(Deserialize)]
pub struct BotDeck {
    pub code: String,
    pub name: String,
    /// Which format this deck is legal for. Absent on the bundled Commander
    /// precons, which predate the field.
    #[serde(default)]
    pub format: Option<String>,
    /// Which game this deck is for. Absent means Magic - every deck predating
    /// the multi-game pools is one.
    #[serde(default)]
    pub game: Option<String>,
    pub cards: Vec<BotDeckCard>,
}

#[derive(Deserialize)]
pub struct BotDeckCard {
    pub sid: String,
    pub name: String,
    pub qty: u32,
    pub board: String,
}

/// The public deck-metrics blob for a bot seat, in the same shape a human
/// client pushes with `deckmeta.set` (see src/app/data/deckMeta.ts).
///
/// Humans compute their own because the server only stores card ids - but a
/// bot has no client to compute anything, so its seat used to carry no metrics
/// at all and every deck-facing affordance went dark against the commonest
/// opponent in the app. The embedded attr table already holds exactly what
/// this needs, so derive it here.
pub fn deck_meta(code: &str) -> Option<serde_json::Value> {
    if let Some(deck) = ygo_data().decks.iter().find(|deck| deck.code == code) {
        return Some(ygo_deck_meta(deck));
    }
    let d = data();
    let deck = d.decks.iter().find(|deck| deck.code == code)?;
    let mut size = 0u64;
    let (mut creatures, mut lands, mut spells, mut other) = (0u64, 0u64, 0u64, 0u64);
    let mut mv_sum = 0f64;
    let mut mv_count = 0u64;
    let mut curve = vec![0u64; 8];
    for card in &deck.cards {
        if card.board == "side" {
            continue;
        }
        let qty = card.qty as u64;
        size += qty;
        let Some(attr) = d.attrs.get(&card.sid) else { continue };
        let is_land = attr.t.contains('L');
        if is_land {
            lands += qty;
        } else if attr.t.contains('C') {
            creatures += qty;
        } else if attr.t.contains('I') || attr.t.contains('S') {
            spells += qty;
        } else {
            other += qty;
        }
        if !is_land {
            mv_sum += attr.mv * qty as f64;
            mv_count += qty;
            let slot = (attr.mv.round().max(0.0) as usize).min(curve.len() - 1);
            curve[slot] += qty;
        }
    }
    let avg_mv = if mv_count > 0 { (mv_sum / mv_count as f64 * 10.0).round() / 10.0 } else { 0.0 };
    // The deck's face. A human seat's cover is picked client-side (deckMeta.ts
    // coverOf: the chosen header, else the commander, else the first card) and
    // synced up; a bot has no client to do that, so the same rule runs here.
    // Without it every bot showed a blank art panel in the pregame lobby and a
    // coverless card in the roster - the tile is gated on deckMeta.cover.
    let cover = deck
        .cards
        .iter()
        .find(|c| c.board == "commander")
        .or_else(|| deck.cards.iter().find(|c| c.board != "side"))
        .map(|c| c.sid.clone());
    Some(serde_json::json!({
        "size": size,
        "cover": cover,
        "creatures": creatures,
        "lands": lands,
        "spells": spells,
        "other": other,
        "avgMv": avg_mv,
        "curve": curve,
    }))
}

/// Per-card attributes: mana value, type letters (subset of LCISAEPB, O =
/// other), and printed power/toughness when present.
#[derive(Deserialize)]
pub struct CardAttr {
    pub mv: f64,
    pub t: String,
    #[serde(default)]
    pub p: Option<String>,
    #[serde(default)]
    pub tg: Option<String>,
}

/// Cards the bundled table does not carry, learned from the oracle as it
/// resolves them.
///
/// The embedded table only ever covers the decks that ship with the server, and
/// a pool generated without attributes is INVISIBLE to the bot: `attr()` misses,
/// so `is_land()` is false for every card, the bot never makes a land drop,
/// never casts, and sits there drawing. A 174-deck Commander pool shipped that
/// way and did exactly that.
///
/// So the oracle - which fetches and caches the real card for anything at the
/// table - fills this in as it goes, and `attr()` falls through to it. That
/// keeps `attr()` a plain function of a card (56 call sites take no `App`), and
/// it is why the fallback the pool generator's comment always claimed now
/// actually exists.
/// The entries are leaked deliberately, so `attr()` can keep handing out
/// `&'static` and its 56 call sites stay untouched. It is bounded by the number
/// of DISTINCT cards the server ever sees - a few tens of thousands of ~64-byte
/// structs at the absolute ceiling of every card ever printed - and each one is
/// written once and read for the life of the process.
static LEARNED: OnceLock<dashmap::DashMap<String, &'static CardAttr>> = OnceLock::new();

fn learned() -> &'static dashmap::DashMap<String, &'static CardAttr> {
    LEARNED.get_or_init(dashmap::DashMap::new)
}

/// Derive the bot's compact view of a card from an oracle row. Called by the
/// oracle whenever it caches one, so the bot learns every card the table sees.
pub fn learn(scryfall_id: &str, type_line: &str, cmc: f64, power: Option<&str>, toughness: Option<&str>) {
    if data().attrs.contains_key(scryfall_id) || learned().contains_key(scryfall_id) {
        return;
    }
    let letters: String = [
        ("Land", 'L'), ("Creature", 'C'), ("Instant", 'I'), ("Sorcery", 'S'),
        ("Artifact", 'A'), ("Enchantment", 'E'), ("Planeswalker", 'P'), ("Battle", 'B'),
    ]
    .iter()
    .filter(|(word, _)| type_line.contains(word))
    .map(|(_, letter)| *letter)
    .collect();
    let entry: &'static CardAttr = Box::leak(Box::new(CardAttr {
        mv: cmc,
        t: if letters.is_empty() { "O".to_string() } else { letters },
        p: power.map(str::to_string),
        tg: toughness.map(str::to_string),
    }));
    learned().insert(scryfall_id.to_string(), entry);
}

static DATA: OnceLock<BotData> = OnceLock::new();

pub fn data() -> &'static BotData {
    DATA.get_or_init(|| {
        let mut data: BotData =
            serde_json::from_str(include_str!("../data/bot_data.json")).expect("bot_data.json parses");
        // The Standard pool is generated separately (scripts/gen-standard-decks.mjs,
        // rerun each rotation) and merged here, so a Standard table has real
        // 60-card opponents instead of a Commander precon.
        let standard: BotData = serde_json::from_str(include_str!("../data/bot_decks_standard.json"))
            .expect("bot_decks_standard.json parses");
        data.decks.extend(standard.decks);
        data.attrs.extend(standard.attrs);
        // Every Commander precon ever printed (scripts/sync-commander-pool.mjs,
        // from MTGJSON). bot_data.json's own four are the bundled Final Fantasy
        // decks that src/data/precons.json also carries for the deck browser;
        // this is the wider pool the dealer draws from, and it is kept separate
        // because precons.json holds the full card record the browser renders
        // and would be ~37MB at this many decks.
        let commander: BotData = serde_json::from_str(include_str!("../data/bot_decks_commander.json"))
            .expect("bot_decks_commander.json parses");
        // Deduped by DECKLIST, not by code. The four bundled Final Fantasy
        // precons are in the synced pool too, under their MTGJSON product names
        // and therefore different codes - so a code comparison keeps both and
        // the pool holds four pairs that play identically, which is exactly the
        // sameness this pool exists to cure. The synced entry wins: it carries
        // a format and a release date the bundled one predates.
        let signature = |deck: &BotDeck| {
            let mut cards: Vec<String> =
                deck.cards.iter().map(|c| format!("{}x{}", c.sid, c.qty)).collect();
            cards.sort();
            cards.join("|")
        };
        let incoming: std::collections::HashSet<String> =
            commander.decks.iter().map(&signature).collect();
        data.decks.retain(|d| !incoming.contains(&signature(d)));
        data.decks.extend(commander.decks);
        for (id, attr) in commander.attrs {
            data.attrs.entry(id).or_insert(attr);
        }
        data
    })
}

// ------------------------------------------------------------ yu-gi-oh data

/// The Yu-Gi-Oh pool, generated by scripts/gen-yugioh-decks.mjs. Kept apart
/// from the Magic table because a duel monster shares nothing with a Magic
/// card: no mana value, no colours, and its two numbers mean different things
/// depending on which way up it is sitting.
#[derive(Deserialize)]
pub struct YgoData {
    pub decks: Vec<BotDeck>,
    pub attrs: HashMap<String, YgoAttr>,
}

/// One duel card as the bot reads it.
#[derive(Deserialize, Clone)]
pub struct YgoAttr {
    /// Kind: `M` monster, `S` spell, `T` trap.
    pub k: String,
    /// Level (or Rank/Link Rating), which fixes the tribute cost.
    #[serde(default)]
    pub lv: i64,
    #[serde(default)]
    pub atk: i64,
    #[serde(default)]
    pub def: i64,
    /// Extra Deck monster: never Normal Summonable from the hand.
    #[serde(default)]
    pub x: bool,
    /// Spell/Trap subtype ("Normal", "Field", "Quick-Play", ...).
    #[serde(default)]
    pub sub: Option<String>,
}

/// A duel deck's public metrics, in the shape a Yu-Gi-Oh client pushes
/// (src/app/data/deckMeta.ts): Main Deck size and split, Extra Deck size, and
/// the average ATK of the monsters.
fn ygo_deck_meta(deck: &BotDeck) -> serde_json::Value {
    let attrs = &ygo_data().attrs;
    let (mut size, mut monsters, mut spells, mut traps, mut extra) = (0u64, 0u64, 0u64, 0u64, 0u64);
    let (mut atk_sum, mut atk_count) = (0i64, 0u64);
    for card in &deck.cards {
        let qty = card.qty as u64;
        if card.board == "commander" {
            extra += qty;
            continue;
        }
        if card.board == "side" {
            continue;
        }
        size += qty;
        let Some(attr) = attrs.get(&card.sid) else { continue };
        match attr.k.as_str() {
            "M" => {
                monsters += qty;
                atk_sum += attr.atk * qty as i64;
                atk_count += qty;
            }
            "S" => spells += qty,
            _ => traps += qty,
        }
    }
    // Same reasoning as the MTG builder above: without a cover the seat's tile
    // has no face to show.
    let cover = deck
        .cards
        .iter()
        .find(|c| c.board != "side")
        .map(|c| c.sid.clone());
    serde_json::json!({
        "size": size,
        "cover": cover,
        "monsters": monsters,
        "spells": spells,
        "traps": traps,
        "extra": extra,
        "avgAtk": if atk_count > 0 { atk_sum / atk_count as i64 } else { 0 },
    })
}

static YGO: OnceLock<YgoData> = OnceLock::new();

pub fn ygo_data() -> &'static YgoData {
    YGO.get_or_init(|| {
        serde_json::from_str(include_str!("../data/bot_decks_yugioh.json"))
            .expect("bot_decks_yugioh.json parses")
    })
}

pub(crate) fn ygo_attr(card: &Card) -> Option<&'static YgoAttr> {
    card.scryfall_id.as_deref().and_then(|sid| ygo_data().attrs.get(sid))
}

/// Tributes a Normal Summon of this Level costs: none through 4, one at 5-6,
/// two from 7 up.
pub(crate) fn tributes_for(level: i64) -> usize {
    if level >= 7 {
        2
    } else if level >= 5 {
        1
    } else {
        0
    }
}

/// The decks a table should draw bots from. A duel table gets the Yu-Gi-Oh
/// pool; a Standard table the 60-card Standard pool; everything else keeps the
/// Commander precons (the historical behaviour, and the right answer for
/// Commander, Brawl and freeform pods alike). Falls back to the whole pool if
/// a format somehow has no decks, so a bot always brings SOMETHING.
pub fn decks_for(game: &str, format: &str) -> Vec<&'static BotDeck> {
    if game == "yugioh" {
        return ygo_data().decks.iter().collect();
    }
    let all = &data().decks;
    let want_standard = format.eq_ignore_ascii_case("standard");
    // A deck with no `format` predates the field and is one of the four bundled
    // Commander precons, so absent reads as commander - which is what keeps
    // them in the Commander pool now that the synced decks all declare it.
    let picked: Vec<&BotDeck> = all
        .iter()
        .filter(|d| {
            let is_standard = d.format.as_deref() == Some("standard");
            is_standard == want_standard
        })
        .collect();
    if picked.is_empty() { all.iter().collect() } else { picked }
}

// ------------------------------------------------------------ card reading

pub fn attr(card: &Card) -> Option<&'static CardAttr> {
    let sid = card.scryfall_id.as_deref()?;
    // Bundled table first (it ships with the server and needs no lookup), then
    // whatever the oracle has taught us about cards outside it.
    data()
        .attrs
        .get(sid)
        .or_else(|| learned().get(sid).map(|e| *e.value()))
}

/// Known to be a land. Cards outside the embedded attribute table (anything
/// beyond the bundled precons) answer `false`, so callers get silence rather
/// than a guess - which is the right failure for both the bot and the coach.
pub fn is_land(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('L')).unwrap_or(false)
}

/// A creature as far as the bot can tell: typed C in the embedded attrs, or
/// carrying printed/declared power (tokens, opponents' declared stats).
pub(crate) fn is_creature(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('C')).unwrap_or(false) || card.power.is_some()
}

/// Instant or sorcery: rides the stack and self-resolves to the graveyard.
pub(crate) fn is_spell(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('I') || a.t.contains('S')).unwrap_or(false)
}

pub(crate) fn mana_value(card: &Card) -> i64 {
    attr(card).map(|a| a.mv.round() as i64).unwrap_or(0)
}

pub(crate) fn stat(s: Option<&str>) -> Option<i64> {
    s.and_then(|v| v.trim().parse::<i64>().ok())
}

pub(crate) fn power(card: &Card) -> i64 {
    stat(card.power.as_deref())
        .or_else(|| attr(card).and_then(|a| stat(a.p.as_deref())))
        .unwrap_or(0)
}

pub(crate) fn toughness(card: &Card) -> i64 {
    stat(card.toughness.as_deref())
        .or_else(|| attr(card).and_then(|a| stat(a.tg.as_deref())))
        .unwrap_or(0)
}

/// Printed power is `*` - a characteristic-defining ability, not a number.
pub(crate) fn starred(card: &Card) -> bool {
    card.power
        .as_deref()
        .or_else(|| attr(card).and_then(|a| a.p.as_deref()))
        .map(|p| p.contains('*'))
        .unwrap_or(false)
}

/// Power as the bot should read it, with a `*` resolved against the board.
/// `power` parses the printed string, so a CDA lands there as 0 - which is
/// exactly why Bronze Guardian never attacked and never blocked usefully. The
/// rules engine counts the ability, so ask it for those cards.
pub(crate) fn power_of(app: &App, room: &Room, card: &Card) -> i64 {
    if starred(card) {
        crate::rules::effective_pt(app, room, card).0
    } else {
        power(card)
    }
}

/// Forge-style creature value for a creature sitting on a board (so a `*`
/// power counts), stripped to the visible stats. Mana value stands in for the
/// rules text the server cannot see: an expensive creature probably does
/// something.
pub(crate) fn eval_creature_at(app: &App, room: &Room, card: &Card) -> i64 {
    100 + 15 * power_of(app, room, card) + 10 * toughness(card) + 5 * mana_value(card)
}

/// The card that a combat entry describes, wherever it currently sits, with
/// its owner's seat. None once it left every battlefield.
pub(crate) fn find_on_battlefields<'a>(room: &'a Room, iid: &str) -> Option<(usize, &'a Card)> {
    room.players.iter().find_map(|p| {
        p.battlefield.iter().find(|c| c.iid == iid).map(|c| (p.seat, c))
    })
}

// -------------------------------------------------------------------- style

#[derive(Clone, Copy, PartialEq)]
pub(crate) enum Style {
    Casual,
    Aggro,
    Defensive,
}

pub(crate) fn style_of(p: &Player) -> Style {
    match p.bot_style.as_deref() {
        Some("aggro") => Style::Aggro,
        Some("defensive") => Style::Defensive,
        _ => Style::Casual,
    }
}

/// Spells the bot is willing to cast in one of its turns (commander is free).
pub(crate) fn cast_budget(style: Style) -> u32 {
    match style {
        Style::Casual => 2,
        Style::Aggro => 3,
        Style::Defensive => 2,
    }
}

/// Baseline aggression on the Forge 0-5 ladder before race math adjusts it.
pub(crate) fn base_aggression(style: Style) -> i32 {
    match style {
        Style::Aggro => 4,
        Style::Casual => 3,
        Style::Defensive => 2,
    }
}

/// Difficulty tier: -1 easy, 0 normal, +1 hard. Shifts aggression and the
/// casting budget; easy also stops gang- and chump-blocking (see choose_block)
/// and keeps almost any opening hand.
pub(crate) fn tier_of(p: &Player) -> i32 {
    match p.bot_difficulty.as_deref() {
        Some("easy") => -1,
        Some("hard") => 1,
        _ => 0,
    }
}


#[cfg(test)]
mod pool_tests {
    use super::*;

    /// A bot has to be able to READ the deck it is dealt.
    ///
    /// Everything the brain decides runs through `attr()`: `is_land()` picks
    /// the land drop, `mana_value()` decides what is castable, `is_creature()`
    /// finds attackers. A card missing from the attribute table is not "unknown
    /// but playable" - it is invisible, and a bot holding a deck of invisible
    /// cards does nothing at all. It draws, and passes, and draws.
    ///
    /// That is not hypothetical: the Commander pool shipped with the four
    /// bundled precons' 339 attributes copied onto its own 174 decks - 2%
    /// coverage - and a Commander bot sat at turn 34 with a 37-card hand and
    /// nothing on the battlefield but its commander. Every other bot test
    /// passed throughout, because they assert that turns advance and the loop
    /// does not stall, which a bot doing nothing satisfies perfectly.
    #[test]
    fn every_pooled_deck_is_readable_by_the_bot() {
        let attrs = &data().attrs;
        for (game, format) in [("mtg", "commander"), ("mtg", "standard")] {
            for deck in decks_for(game, format) {
                let unknown = deck.cards.iter().filter(|c| !attrs.contains_key(&c.sid)).count();
                assert_eq!(
                    unknown, 0,
                    "{format} deck {:?} has {unknown}/{} cards the bot cannot read",
                    deck.name,
                    deck.cards.len(),
                );
            }
        }
    }

    /// The land drop specifically, since it is the first thing a bot does and
    /// the first thing anyone notices it not doing.
    #[test]
    fn every_pooled_deck_has_lands_the_bot_can_find() {
        let attrs = &data().attrs;
        for (game, format) in [("mtg", "commander"), ("mtg", "standard")] {
            for deck in decks_for(game, format) {
                let lands = deck
                    .cards
                    .iter()
                    .filter(|c| attrs.get(&c.sid).map(|a| a.t.contains('L')).unwrap_or(false))
                    .count();
                assert!(lands > 0, "{format} deck {:?} has no land the bot can identify", deck.name);
            }
        }
    }

    /// The pool the Commander roulette actually deals from.
    #[test]
    fn commander_pool_is_the_whole_precon_history() {
        let pool = decks_for("mtg", "commander");
        // Every Commander precon MTGJSON knows about, minus Collector's
        // Editions and minus the reprints that duplicate an earlier decklist.
        assert!(pool.len() > 150, "commander pool is only {}", pool.len());
        // A five-seat pod deals without replacement, so it needs at least five.
        assert!(pool.len() >= 5);
    }

    #[test]
    fn standard_and_commander_pools_do_not_overlap() {
        let commander = decks_for("mtg", "commander");
        let standard = decks_for("mtg", "standard");
        assert!(!standard.is_empty());
        for deck in &commander {
            assert_ne!(deck.format.as_deref(), Some("standard"), "{} leaked", deck.code);
        }
        for deck in &standard {
            assert_eq!(deck.format.as_deref(), Some("standard"), "{} leaked", deck.code);
        }
    }

    /// The dealer keys a dealt deck as `precon:<code>` and avoids duplicates by
    /// comparing codes, so two decks under one code are one deck to it.
    #[test]
    fn every_deck_code_is_unique() {
        let mut codes: Vec<&str> = data().decks.iter().map(|d| d.code.as_str()).collect();
        codes.sort_unstable();
        let before = codes.len();
        codes.dedup();
        assert_eq!(before, codes.len(), "duplicate deck codes in the merged pool");
    }

    /// Two entries with the same decklist are two decks that play identically -
    /// which is the exact complaint this pool was widened to fix.
    #[test]
    fn no_two_decks_share_a_decklist() {
        let mut lists: Vec<String> = data()
            .decks
            .iter()
            .map(|d| {
                let mut cards: Vec<String> =
                    d.cards.iter().map(|c| format!("{}x{}", c.sid, c.qty)).collect();
                cards.sort();
                cards.join("|")
            })
            .collect();
        lists.sort();
        let before = lists.len();
        lists.dedup();
        assert_eq!(before, lists.len(), "two decks in the pool have identical decklists");
    }

    /// A Commander deck with no commander seats a player with no general.
    #[test]
    fn every_commander_deck_has_a_commander() {
        for deck in decks_for("mtg", "commander") {
            assert!(
                deck.cards.iter().any(|c| c.board == "commander"),
                "{} has no commander",
                deck.code
            );
        }
    }
}
