//! What the bot can KNOW: the embedded precon data, card attribute reads,
//! creature evaluation, and per-seat style/tier - facts, never decisions.

use super::*;

// ------------------------------------------------------------ embedded data

/// Generated by scripts/gen-bot-data.mjs from src/data/precons.json.
#[derive(Deserialize)]
pub struct BotData {
    pub decks: Vec<BotDeck>,
    pub attrs: HashMap<String, CardAttr>,
}

#[derive(Deserialize)]
pub struct BotDeck {
    pub code: String,
    pub name: String,
    pub cards: Vec<BotDeckCard>,
}

#[derive(Deserialize)]
pub struct BotDeckCard {
    pub sid: String,
    pub name: String,
    pub qty: u32,
    pub board: String,
}

/// The public deck-metrics blob for a bot seat, in the same shape a human
/// client pushes with `deckmeta.set` (see src/app/data/deckMeta.ts).
///
/// Humans compute their own because the server only stores card ids - but a
/// bot has no client to compute anything, so its seat used to carry no metrics
/// at all and every deck-facing affordance went dark against the commonest
/// opponent in the app. The embedded attr table already holds exactly what
/// this needs, so derive it here.
pub fn deck_meta(code: &str) -> Option<serde_json::Value> {
    let d = data();
    let deck = d.decks.iter().find(|deck| deck.code == code)?;
    let mut size = 0u64;
    let (mut creatures, mut lands, mut spells, mut other) = (0u64, 0u64, 0u64, 0u64);
    let mut mv_sum = 0f64;
    let mut mv_count = 0u64;
    let mut curve = vec![0u64; 8];
    for card in &deck.cards {
        if card.board == "side" {
            continue;
        }
        let qty = card.qty as u64;
        size += qty;
        let Some(attr) = d.attrs.get(&card.sid) else { continue };
        let is_land = attr.t.contains('L');
        if is_land {
            lands += qty;
        } else if attr.t.contains('C') {
            creatures += qty;
        } else if attr.t.contains('I') || attr.t.contains('S') {
            spells += qty;
        } else {
            other += qty;
        }
        if !is_land {
            mv_sum += attr.mv * qty as f64;
            mv_count += qty;
            let slot = (attr.mv.round().max(0.0) as usize).min(curve.len() - 1);
            curve[slot] += qty;
        }
    }
    let avg_mv = if mv_count > 0 { (mv_sum / mv_count as f64 * 10.0).round() / 10.0 } else { 0.0 };
    Some(serde_json::json!({
        "size": size,
        "creatures": creatures,
        "lands": lands,
        "spells": spells,
        "other": other,
        "avgMv": avg_mv,
        "curve": curve,
    }))
}

/// Per-card attributes: mana value, type letters (subset of LCISAEPB, O =
/// other), and printed power/toughness when present.
#[derive(Deserialize)]
pub struct CardAttr {
    pub mv: f64,
    pub t: String,
    #[serde(default)]
    pub p: Option<String>,
    #[serde(default)]
    pub tg: Option<String>,
}

static DATA: OnceLock<BotData> = OnceLock::new();

pub fn data() -> &'static BotData {
    DATA.get_or_init(|| {
        serde_json::from_str(include_str!("../data/bot_data.json")).expect("bot_data.json parses")
    })
}

// ------------------------------------------------------------ card reading

pub fn attr(card: &Card) -> Option<&'static CardAttr> {
    card.scryfall_id.as_deref().and_then(|sid| data().attrs.get(sid))
}

/// Known to be a land. Cards outside the embedded attribute table (anything
/// beyond the bundled precons) answer `false`, so callers get silence rather
/// than a guess - which is the right failure for both the bot and the coach.
pub fn is_land(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('L')).unwrap_or(false)
}

/// A creature as far as the bot can tell: typed C in the embedded attrs, or
/// carrying printed/declared power (tokens, opponents' declared stats).
pub(crate) fn is_creature(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('C')).unwrap_or(false) || card.power.is_some()
}

/// Instant or sorcery: rides the stack and self-resolves to the graveyard.
pub(crate) fn is_spell(card: &Card) -> bool {
    attr(card).map(|a| a.t.contains('I') || a.t.contains('S')).unwrap_or(false)
}

pub(crate) fn mana_value(card: &Card) -> i64 {
    attr(card).map(|a| a.mv.round() as i64).unwrap_or(0)
}

pub(crate) fn stat(s: Option<&str>) -> Option<i64> {
    s.and_then(|v| v.trim().parse::<i64>().ok())
}

pub(crate) fn power(card: &Card) -> i64 {
    stat(card.power.as_deref())
        .or_else(|| attr(card).and_then(|a| stat(a.p.as_deref())))
        .unwrap_or(0)
}

pub(crate) fn toughness(card: &Card) -> i64 {
    stat(card.toughness.as_deref())
        .or_else(|| attr(card).and_then(|a| stat(a.tg.as_deref())))
        .unwrap_or(0)
}

/// Printed power is `*` - a characteristic-defining ability, not a number.
pub(crate) fn starred(card: &Card) -> bool {
    card.power
        .as_deref()
        .or_else(|| attr(card).and_then(|a| a.p.as_deref()))
        .map(|p| p.contains('*'))
        .unwrap_or(false)
}

/// Power as the bot should read it, with a `*` resolved against the board.
/// `power` parses the printed string, so a CDA lands there as 0 - which is
/// exactly why Bronze Guardian never attacked and never blocked usefully. The
/// rules engine counts the ability, so ask it for those cards.
pub(crate) fn power_of(app: &App, room: &Room, card: &Card) -> i64 {
    if starred(card) {
        crate::rules::effective_pt(app, room, card).0
    } else {
        power(card)
    }
}

/// Forge-style creature value for a creature sitting on a board (so a `*`
/// power counts), stripped to the visible stats. Mana value stands in for the
/// rules text the server cannot see: an expensive creature probably does
/// something.
pub(crate) fn eval_creature_at(app: &App, room: &Room, card: &Card) -> i64 {
    100 + 15 * power_of(app, room, card) + 10 * toughness(card) + 5 * mana_value(card)
}

/// The card that a combat entry describes, wherever it currently sits, with
/// its owner's seat. None once it left every battlefield.
pub(crate) fn find_on_battlefields<'a>(room: &'a Room, iid: &str) -> Option<(usize, &'a Card)> {
    room.players.iter().find_map(|p| {
        p.battlefield.iter().find(|c| c.iid == iid).map(|c| (p.seat, c))
    })
}

// -------------------------------------------------------------------- style

#[derive(Clone, Copy, PartialEq)]
pub(crate) enum Style {
    Casual,
    Aggro,
    Defensive,
}

pub(crate) fn style_of(p: &Player) -> Style {
    match p.bot_style.as_deref() {
        Some("aggro") => Style::Aggro,
        Some("defensive") => Style::Defensive,
        _ => Style::Casual,
    }
}

/// Spells the bot is willing to cast in one of its turns (commander is free).
pub(crate) fn cast_budget(style: Style) -> u32 {
    match style {
        Style::Casual => 2,
        Style::Aggro => 3,
        Style::Defensive => 2,
    }
}

/// Baseline aggression on the Forge 0-5 ladder before race math adjusts it.
pub(crate) fn base_aggression(style: Style) -> i32 {
    match style {
        Style::Aggro => 4,
        Style::Casual => 3,
        Style::Defensive => 2,
    }
}

/// Difficulty tier: -1 easy, 0 normal, +1 hard. Shifts aggression and the
/// casting budget; easy also stops gang- and chump-blocking (see choose_block)
/// and keeps almost any opening hand.
pub(crate) fn tier_of(p: &Player) -> i32 {
    match p.bot_difficulty.as_deref() {
        Some("easy") => -1,
        Some("hard") => 1,
        _ => 0,
    }
}

