import idManifest from '../../data/precon-ids.json' with { type: 'json' };

/**
 * Card-image resolution plus the precon type shapes.
 *
 * This is the LIGHT half of the precon data: the whole app calls cardImage/
 * artCrop during render, so it must stay in the initial payload - but it needs
 * only the tiny id manifest (which cards ship bundled) to choose the local
 * cache over Scryfall's CDN, NOT the full 850KB decklists. Those live in
 * precons.ts, imported lazily. The manifest is regenerated by
 * scripts/sync-precons.mjs alongside precons.json.
 */

export interface PreconCard {
  id: string;
  oracleId: string;
  name: string;
  quantity: number;
  board: string;
  manaCost: string;
  manaValue: number;
  typeLine: string;
  oracleText: string;
  colors: string[];
  colorIdentity: string[];
  rarity?: string;
  artist?: string;
  flavorText?: string;
  power?: string;
  toughness?: string;
}

export interface Precon {
  id: string;
  name: string;
  code: string;
  releaseDate: string;
  format: string;
  productType: string;
  strategy: string;
  cards: PreconCard[];
}

const manifest = idManifest as { ids: string[]; commanderIds: string[] };

/** Every bundled printing, for cache-aware image resolution. */
const BUNDLED_IDS = new Set<string>(manifest.ids);

/** Bundled art crops - commanders only (hero imagery on Profile/Decks). */
const BUNDLED_ART = new Set<string>(manifest.commanderIds);

const BASE = import.meta.env.BASE_URL;

/** The `normal`-size card front for any Scryfall id: bundled cache first, CDN otherwise. */
export function cardImage(scryfallId: string | undefined): string {
  if (!scryfallId) return '';
  if (BUNDLED_IDS.has(scryfallId)) return `${BASE}cache/cards/${scryfallId}.jpg`;
  return `https://cards.scryfall.io/normal/front/${scryfallId[0]}/${scryfallId[1]}/${scryfallId}.jpg`;
}

/** Bundled art crop - commanders only (hero imagery on Profile/Decks). */
export function commanderArt(scryfallId: string): string {
  return `${BASE}cache/art/${scryfallId}.jpg`;
}

/**
 * The server's deck covers are `api.scryfall.com/cards/{id}?format=image`
 * redirects (full card scans, border included). Pull the id back out so
 * surfaces that want pure artwork can use the art crop instead.
 */
export function coverArtCrop(coverImageUrl: string | undefined): string {
  const match = coverImageUrl?.match(/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/);
  return match ? artCrop(match[1]) : (coverImageUrl ?? '');
}

/** The wide art-crop for any card: bundled for precon commanders, CDN otherwise. */
export function artCrop(scryfallId: string | undefined): string {
  if (!scryfallId) return '';
  if (BUNDLED_ART.has(scryfallId)) return commanderArt(scryfallId);
  return `https://cards.scryfall.io/art_crop/front/${scryfallId[0]}/${scryfallId[1]}/${scryfallId}.jpg`;
}

/** WUBRG order for pips and identity chips. */
export const COLOR_ORDER = ['W', 'U', 'B', 'R', 'G'] as const;

export const COLOR_NAMES: Record<string, string> = {
  W: 'White',
  U: 'Blue',
  B: 'Black',
  R: 'Red',
  G: 'Green',
};
